<?php
    
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
    //$users  = isset($users) ? $users : '';//uuids dos usuarios
    $validate = isset($message['validate']) ? $message['validate'] : '';//mensagem do validador dos campos
    $user_type = $_SESSION['user']['user_type'];//tipo de usuario
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Lista Login</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="template/dist/css/AdminLTE.min.css">
        <!-- Data Table -->
        <link rel="stylesheet" href="/template/bower_components/datatables.net-bs/css/dataTables.bootstrap.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link rel="stylesheet" href="template/bower_components/select2/dist/css/select2.min.css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script>
		   // $('.select2').select2();
	    </script>
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        <div class="wrapper">

            <?php include_once(__DIR__.'/../header.phtml'); ?>
            
            <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Login
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Listar Usuário</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                            

                                        <form id="myForm" class="form-horizontal" action="" method="get">
                                            <div class="box-body">
                                                <div class="form-group" id="div_busca">
                                                    <label class="col-sm-2 control-label">Tipo de busca:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_busca' name="busca" class="normal form-control select2" onchange="
                                                            $('#lbl_dado').html($('#opt_busca option:selected').html()+':');
                                                            if($('#opt_busca').val() != '')
                                                                $('#div_dado').show();
                                                            else
                                                                $('#div_dado').hide();

                                                            $('#txt_dado').val('');
                                                        ">
                                                            <option value="">Selecione o tipo de busca</option>
                                                            <option value="1">E-mail</option>
                                                            <option value="2">CPF</option>
                                                            <option value="3">Nome</option>
                                                        </select>
                                                    </div>    
                                                </div>
                                                <div class="form-group" id="div_dado" style="display:none">
                                                    <label class="col-sm-2 control-label" id="lbl_dado"></label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_dado" name="dado" onkeyup="
                                                            if($('#opt_busca').val() == '2'){
                                                                var cpf = $('#txt_dado').val();
                                                                cpf = cpf.replace(/\D+/g, '');
                                                                $('#txt_dado').val(cpf);
                                                            }
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_busca">
                                                    <label class="col-sm-2 control-label">Status:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_status' name="status" class="normal form-control select2" onchange="">
                                                            <option value="">Selecione o Status</option>
                                                            <option value="1">Ativo</option>
                                                            <option value="2" selected>Pendente</option>
                                                            <option value="3">Desativado</option>
                                                        </select>
                                                    </div>    
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-sm-3 col-sm-offset-2">
                                                        <button id="buscar" type="button" class="btn btn-primary" onclick="listaUsuarios()">Buscar</button>
                                                    </div>
                                                </div>
                                            </div>    
                                        
                                    </div>
                                </div><!--box-body-->
                            </div>
                        </div>    
                    </div><!--row-->    

                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Lista de Usuários</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-sm-12 col-xs-6">
                                            
                                                <div id="div_lista">
                                                    <div class="table-responsive">
                                                        <div id="id_tabela" style="max-height: 500px;overflow-y: auto;">
                                                            <table id="tbUsuario" class="table table-bordered table-striped">
                                                                <thead>
                                                                    <tr>
                                                                        <th width="300">Nome</th>
                                                                        <th>Email</th>
                                                                        <th>CPF</th>
                                                                        <th>Tipo</th>
                                                                        <th>Status</th>  

                                                                        <?php if($user_type == 1 || $user_type == 2){?>
                                                                            <th width="10"><i class="fa fa-edit"></i></th>
                                                                            <th width="10"><i class="fa fa-trash-o"></i></th>
                                                                        <?php }?>    
                                                                    </tr>
                                                                </thead>
                                                                <tbody  id="tbUsuarioBody">

                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>	
                                                </div><!-- Fim his_buscas -->
                                            
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->


                </section> <!--content-->   
            </div><!--corpoGeral-->  
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div><!-- wrapper -->


        <script src="template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		<!-- daterangepicker -->
		<script src="template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
		<script src="template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="template/bower_components/select2/dist/js/select2.min.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <!-- jQuery 3 -->
        <!-- <script src="template/bower_components/jquery/dist/jquery.min.js"></script> -->
        <!-- Bootstrap 3.3.7 -->
        <!-- <script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script> -->
        <!-- iCheck -->
        <!-- <script src="template/plugins/iCheck/icheck.min.js"></script> -->

        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->

        <script>
        $('.select2').select2();
        listaUsuarios();
            // function atualizaUsuario(nome,valor){
            //     $.ajax({
            //         type: 'POST',
            //         url: 'filtroUserLista',
            //         dataType: 'json',
            //         data: 'nome='+nome+'&valor='+valor,
            //         success: function(resposta){
            //             $('#opt_user').empty();
            //             $("#opt_user").append(new Option('Selecione um usuário', ''));
            //             for(var i=0; i<resposta.length;i++){
            //                 $("#opt_user").append(new Option(resposta[i]['name'], resposta[i]['uuid']));
            //             }
            //         }
            //     });
            // }

            function listaUsuarios(){
                var tabela = '';
                var status = '';
                var tipo = '';
                var nome = '';
                var valor = '';

                if($('#txt_dado').val() == '' && $('#opt_busca').val() != '' && $('#opt_status').val() == '' ||
                $('#opt_busca').val() == '' && $('#opt_status').val() == ''
                ){
                    toastr.warning('Digite um valor para a busca');
                    return false;
                }

                if($('#opt_status').val() != '')  status = 'status='+$('#opt_status').val();

                if($('#opt_busca').val() == 1){
                    var nome = 'nome=email';
                    if($('#opt_status').val() != '')  status = '&'+status;
                }
                else if($('#opt_busca').val() == 2){
                    var nome = 'nome=cpf';
                    if($('#opt_status').val() != '')  status = '&'+status;
                }
                else if($('#opt_busca').val() == 3){
                    var nome = 'nome=name';
                    if($('#opt_status').val() != '')  status = '&'+status;
                }
                
                if($('#txt_dado').val() == ''){
                    var valor = "";    
                }
                else{
                    var valor = '&valor='+$('#txt_dado').val();
                }

                

                $.ajax({
                    type: 'POST',
                    url: 'filtroUserLista',
                    dataType: 'json',
                    data: nome+valor+status,
                    success: function(resposta){
                        if(resposta == null) toastr.warning('Nenhum dado encontrado!');
                        else{
                            var t = $('#tbUsuario').dataTable();t.fnDestroy();
                            for(var i=0; i<resposta.length;i++){
                                if(resposta[i]['status'] == 1) status = "<td style='color:green'><b>Ativado</b>";
                                else if(resposta[i]['status'] == 2) status = "<td style='color:orange'><b>Pendente</b>";
                                else status = "<td style='color:red'><b>Desativado</b>";
                                
                                if(resposta[i]['user_type'] == 1) tipo = "Super";
                                else if(resposta[i]['user_type'] == 2) tipo = "Admin";
                                else if(resposta[i]['user_type'] == 3) tipo = "Consultor";
                                else tipo = "Usuário";

                                tabela += '<tr id="'+i+'">';
                                tabela += '<td>'+resposta[i]['name']+'</td>';
                                tabela += '<td>'+resposta[i]['email']+'</td>';
                                tabela += '<td>'+resposta[i]['cpf']+'</td>';
                                tabela += '<td>'+tipo+'</td>';
                                tabela += status+'</td>';
                                <?php if($user_type == 1 || $user_type == 2){?>
                                    tabela += '<td><button onclick="editarUsuario(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                                    
                                    if(resposta[i]['user_type'] != 1){
                                        tabela += '<td><button onclick="excluirUsuario(\''+resposta[i]['uuid']+'\',\''+i+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-trash-o"></i></button></td>';
                                    }
                                <?php }?>
                                tabela += '</tr>';
                            }
                            $('#tbUsuarioBody').html(tabela);

                            $('#tbUsuario').DataTable({
                                'autoWidth'   : true,
                                'aLengthMenu' :	[[10, 25, 50, -1], [10, 25, 50, "Tudo"]],
                                'oLanguage'   : {"sEmptyTable": "Nenhum registro encontrado", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando 0 até 0 de 0 registros", "sInfoFiltered": "(Filtrados de _MAX_ registros)", "sInfoPostFix": "", "sInfoThousands": ".", "sLengthMenu": "_MENU_ resultados por página", "sLoadingRecords": "Carregando...", "sProcessing": "Processando...", "sZeroRecords": "Nenhum registro encontrado", "sSearch": "Pesquisar", "oPaginate": { "sNext": "Próximo", "sPrevious": "Anterior", "sFirst": "Primeiro", "sLast": "Último" }, "oAria": { "sSortAscending": ": Ordenar colunas de forma ascendente", "sSortDescending": ": Ordenar colunas de forma descendente"}}
                            });
                        }    
                    }
                });
            }

            function editarUsuario(uuid){
                $("#myForm").attr("action","editaLogin/"+uuid);    
                $("#myForm").submit();
            }

            function excluirUsuario(uuid, num){
                if(confirm("Deseja deletar o usuário?")){
                    $.ajax({
                    type: 'POST',
                    url: 'excluiUsuario',
                    dataType: 'json',
                    data: 'uuid='+uuid,
                    success: function(resposta){
                        if(resposta){
                            $("#"+num+"").remove();
                            toastr.success('Deletado');
                        }
                    }
                    
                    });
                }
            }

            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
                
                // $.ajax({
                //     type: 'POST',
                //     url: 'filtroUserLista',
                //     dataType: 'json',
                //     data: 'nome=email&valor=@',
                //     success: function(resposta){
                //         $('#opt_user').empty();
                //         $("#opt_user").append(new Option('Selecione um usuário', ''));
                //         for(var i=0; i<resposta.length;i++){
                //             $("#opt_user").append(new Option(resposta[i]['name'], resposta[i]['uuid']));
                //         }
                //     }
                // });
                

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                 ?>
			});
        </script>	
    </body>
</html>