
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <!-- <div class="pull-left image"> -->
                    <!-- <div class="img-circle" style="background:url('<?php //echo $imagemLogo; ?>') no-repeat center center; background-size:contain; width:45px; height:45px;"></div>-->
                    <!-- <img src='<?php //echo $imagemLogo; ?>' class="img-circle" alt="User Image" style="width: 100%;max-width: 40px;height: 40px;margin-left: 10px;"/>  -->
                    <!-- <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" /> -->
                <!-- </div>
                <div class="pull-left info">
                    <p><?php echo $_SESSION['user']['name']; ?></p>
                </div> -->
            </div>
            
            <ul class="sidebar-menu">
                <li class="header">Navegação Principal</li>

                <li >
                    <a href="dashboard">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span> </i>
                    </a>
                </li>

                <li >
                    <a href="/cadastroLogin">
                        <i class="fa fa-users"></i> <span>Cadastro Login</span> </i>
                    </a>
                </li>


                <!-- ## Section Logins / Empresas ## -->

                
                <li class="treeview">
                    <a href="#"><i class="fa fa-users"></i><span>Usuários</span><i class="fa fa-angle-left pull-right"></i></a>
                    
                    <ul class="treeview-menu">
                        <li class="treeview">
                            <a href="#"><i class="fa fa-circle-o"></i>Usuário<i class="fa fa-angle-left pull-right"></i></a>
                
                            <ul class="treeview-menu">
                                <li>
                                <a href="/cadastroLogin"><i class="fa fa-circle-o"></i>Adicionar</i></a>
                                    
                                </li>


                                <li>
                                <a href="/editarLogin"><i class="fa fa-circle-o"></i>Editar</i></a>             
                            
                                  
                                </li>
                            </ul>
                        </li>

                        <li class="treeview">
                            <a href="#"><i class="fa fa-circle-o"></i>Compania<i class="fa fa-angle-left pull-right"></i></a>
                
                            <ul class="treeview-menu">
                                <li>
                                <a href="/cadastroCompania"><i class="fa fa-circle-o"></i>Adicionar</i></a>
                                    
                                </li>


                                <li>
                                <a href="/editarCompania"><i class="fa fa-circle-o"></i>Editar</i></a>             
                            
                                  
                                </li>
                            </ul>
                        </li>


                    </ul>
                </li>


                <li >
                    <a href="/cadastroIndicacao">
                        <i class="fa fa-handshake-o"></i> <span>Indicacoes</span> </i>
                    </a>
                </li>


            </ul> <!-- ./ siderbar-menu -->


        </section>
        <!-- /.sidebar -->
    </aside>
    
    