<?php
    
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
    //$companies = isset($companies) ? $companies : '';//uuids das companias
    $services = isset($services) ? $services : '';//uuids dos servicos
    $indication = isset($indication) ? $indication : '';//indicacao
    $consultores = isset($consultores) ? $consultores : '';//consultores
    $validate = isset($message['validate']) ? $message['validate'] : '';//mensagem do validador dos campos
    $user_type = $_SESSION['user']['user_type'];//tipo de usuario

?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Cadastro Contrato</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
      <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/template/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/template/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/template/bower_components/Ionicons/css/ionicons.min.css">
  <!-- daterange picker -->
  <link rel="stylesheet" href="/template/bower_components/bootstrap-daterangepicker/daterangepicker.css">
  <!-- bootstrap datepicker -->
  <link rel="stylesheet" href="/template/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="/template/plugins/iCheck/all.css">
  <!-- Bootstrap Color Picker -->
  <link rel="stylesheet" href="/template/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css">
  <!-- Bootstrap time Picker -->
  <link rel="stylesheet" href="/template/plugins/timepicker/bootstrap-timepicker.min.css">
  <!-- Select2 -->
  <link rel="stylesheet" href="/template/bower_components/select2/dist/css/select2.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/template/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/template/dist/css/skins/_all-skins.min.css">

  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script>
		   // $('.select2').select2();
	    </script>
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        <div class="wrapper">

            <?php include_once(__DIR__.'/../header.phtml'); ?>
            
            <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Contrato
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Cadastrar Contrato</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                            

                                        <form id="myForm" class="form-horizontal" action="../cadastrarContrato" method="post" enctype="multipart/form-data">
                                            <div class="box-body">
                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">Razão Social:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_corporate" name="corporate" placeholder="Razão Social" onkeyup="revisaCampos();">
                                                    </div>
                                                </div>

                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Valor Contrato:</label>
                                                    <div class="col-sm-3">
                                                        <input type="text" maxlength="30" class="form-control" id="txt_value_contract" name="value_contract2" placeholder="Valor" value="00,00" onchange="revisaCampos();tratarValor('txt_value_contract');">
                                                        <input type="hidden" id="txt_value_contract2" name="value_contract" value="0000">
                                                    </div>
                                                </div>

                                                
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">data:</label>
                                                    <div class="col-sm-3">
                                                        <input type="text" class="form-control" data-date-format="dd/mm/yyyy" name="date" id="txt_date" placeholder="Data">
                                                    </div>
                                                </div>

                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Observação:</label>
                                                    <div class="col-sm-6">
                                                        <textarea type="text" class="form-control" name="observation" id="txt_observation" placeholder="Observação" style="resize: none"></textarea>
                                                    </div>
                                                </div>

                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Nr. Identificação:</label>
                                                    <div class="col-sm-6">
                                                    <input type="text" class="form-control" name="indentification" id="txt_indentification" placeholder="Identificação">
                                                    </div>
                                                </div>

                                               
                                                <!-- restrito para admin e super -->
                                                <div id="div_admin">
                                                    <div class="form-group has-feedback">
                                                        <label class="col-sm-2 control-label">Comissão:</label>
                                                        <div class="col-sm-6">
                                                            <select  id='opt_commission' name="commission" class="normal form-control select2" style="width: 125px;display:inline-block;" onchange="revisaCampos();">
                                                                <option value="">Selecione o tipo de comissão</option>
                                                                <option value="1" selected>Fixa</option>
                                                                <option value="2">Recorrente</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <div id="div_data" style="display:none;">
                                                        <div class="form-group has-feedback">
                                                            <label class="col-sm-2 control-label">Data início:</label>
                                                            <div class="col-sm-10">
                                                                <select  id='opt_start_data_m' name="start_data_m" class="normal form-control" style="width: 125px;display: inline-block;" onchange="revisaCampos();
                                                                    $('#txt_start_date').val($('#opt_start_data_y').val()+'-'+$('#opt_start_data_m').val()+'-01');
                                                                ">
                                                                    <?php 
                                                                        for($i=0;$i<12; $i++){
                                                                            if($i+1 == date('m')){
                                                                                echo("<option value='".($i+1)."' selected>".($i+1)."</option>");
                                                                            }else{
                                                                                echo("<option value='".($i+1)."'>".($i+1)."</option>");
                                                                            }
                                                                        }
                                                                    ?>
                                                                </select> /
                                                                <select  id='opt_start_data_y' name="start_data_y" class="normal form-control" style="width: 125px;display:inline-block;" onchange="revisaCampos();
                                                                    $('#txt_start_date').val($('#opt_start_data_y').val()+'-'+$('#opt_start_data_m').val()+'-01');
                                                                    if($('#opt_start_data_y').val() > $('#opt_end_data_y').val()){
                                                                        alert('A data de início deve ser menor que a data final');
                                                                    }
                                                                ">
                                                                    <?php 
                                                                        for($i=0;$i<5; $i++){
                                                                            if($i == 0){
                                                                                echo("<option value='".date('Y')."' selected>".date('Y')."</option>");
                                                                            }else{
                                                                                echo("<option value='".(date('Y')+$i)."'>".(date('Y')+$i)."</option>");
                                                                            }
                                                                        }
                                                                    ?>
                                                                </select>
                                                                <input type="hidden" id="txt_start_date" name="start_date" value="<?php echo(date('Y').'-'.date('m').'-01');?>">
                                                            </div>
                                                        </div>
                                                        <div class="form-group has-feedback">
                                                            <label class="col-sm-2 control-label">Data fim:</label>
                                                            <div class="col-sm-10">
                                                                <select  id='opt_end_data_m' name="end_data_m" class="normal form-control" style="width: 125px;display: inline-block;" onchange="revisaCampos();
                                                                    $('#txt_end_date').val($('#opt_end_data_y').val()+'-'+$('#opt_end_data_m').val()+'-01');
                                                                ">
                                                                    <?php 
                                                                        for($i=0;$i<12; $i++){
                                                                            if($i+1 == date('m')){
                                                                                echo("<option value='".($i+1)."' selected>".($i+1)."</option>");
                                                                            }else{
                                                                                echo("<option value='".($i+1)."'>".($i+1)."</option>");
                                                                            }
                                                                        }
                                                                    ?>
                                                                </select> /
                                                                <select  id='opt_end_data_y' name="end_data_y" class="normal form-control" style="width: 125px;display:inline-block;" onchange="revisaCampos();
                                                                    $('#txt_end_date').val($('#opt_end_data_y').val()+'-'+$('#opt_end_data_m').val()+'-01');
                                                                    if($('#opt_start_data_y').val() > $('#opt_end_data_y').val()){
                                                                        alert('A data de início deve ser menor que a data final');
                                                                    }
                                                                ">
                                                                    <?php 
                                                                        for($i=0;$i<10; $i++){
                                                                            if($i == 0){
                                                                                echo("<option value='".date('Y')."' selected>".date('Y')."</option>");
                                                                            }else{
                                                                                echo("<option value='".(date('Y')+$i)."'>".(date('Y')+$i)."</option>");
                                                                            }
                                                                        }
                                                                    ?>
                                                                </select>
                                                                <input type="hidden" id="txt_end_date" name="end_date" value="<?php echo(date('Y').'-'.date('m').'-01');?>">
                                                            </div>
                                                        </div>
                                                        <div class="form-group has-feedback">
                                                            <label class="col-sm-2 control-label">Observação para as Comissões:</label>
                                                            <div class="col-sm-6">
                                                                <textarea type="text" class="form-control" name="observation_commissions" id="txt_observation_commissions" placeholder="Observação" style="resize: none"></textarea>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="form-group has-feedback">
                                                        <label class="col-sm-2 control-label">Dia do Pagamento:</label>
                                                        <div class="col-sm-3">
                                                            <select  id='opt_day' name="day" class="normal form-control" style="width: 125px;display:inline-block;" onchange="revisaCampos();">
                                                                <option value='01' selected>01</option>
                                                                <option value='02'>02</option>
                                                                <option value='03'>03</option>
                                                                <option value='04'>04</option>
                                                                <option value='05'>05</option>
                                                                <option value='06'>06</option>
                                                                <option value='07'>07</option>
                                                                <option value='08'>08</option>
                                                                <option value='09'>09</option>
                                                                <option value='10'>10</option>
                                                                <option value='11'>11</option>
                                                                <option value='12'>12</option>
                                                                <option value='13'>13</option>
                                                                <option value='14'>14</option>
                                                                <option value='15'>15</option>
                                                                <option value='16'>16</option>
                                                                <option value='17'>17</option>
                                                                <option value='18'>18</option>
                                                                <option value='19'>19</option>
                                                                <option value='20'>20</option>
                                                                <option value='21'>21</option>
                                                                <option value='22'>22</option>
                                                                <option value='23'>23</option>
                                                                <option value='24'>24</option>
                                                                <option value='25'>25</option>
                                                                <option value='26'>26</option>
                                                                <option value='27'>27</option>
                                                                <option value='28'>28</option>
                                                                <option value='29'>29</option>
                                                                <option value='30'>30</option>
                                                                <option value='31'>31</option>
                                                            </select>
                                                        </div>
                                                    </div>

                                                    <div class="form-group has-feedback">
                                                        <label class="col-sm-2 control-label">Valor Comissão:</label>
                                                        <div class="col-sm-3">
                                                            <input type="text" maxlength="30" class="form-control" id="txt_value_commission" name="value_commission2" placeholder="Valor" value="00,00" onchange="revisaCampos();tratarValor('txt_value_commission');">
                                                            <input type="hidden" id="txt_value_commission2" name="value_commission" value="0000">
                                                        </div>
                                                    </div>

                                                    <div class="form-group has-feedback">
                                                        <label class="col-sm-2 control-label">Anexo Contrato:</label>
                                                        <div class="col-sm-6">
                                                            <input type="file" class="form-control" name="anexo[]" multiple="">
                                                        </div>
                                                    </div>
                                                    

                                                    <input type="hidden" id="txt_consultor" name="consultor" value="<?php echo $indication['user_uuid'] ?>">
                                                    <input type="hidden" id="txt_indication" name="indication_uuid" value="<?php echo $indication['uuid'] ?>">
                                                   
                                                </div>    
                                                
                                                
                                                <div class="form-group">
                                                    <div class="col-sm-3 col-sm-offset-2">
                                                        <button id="btn_cadastrar" type="submit" class="btn btn-primary" onclick="" disabled="true">Cadastrar</button>
                                                    </div>
                                                </div>
                                            </div>    
                                        </form>
                                    </div>
                                </div><!--box-body-->
                            </div>
                        </div>    
                    </div><!--row-->    
                </section> <!--content-->   
            </div><!--corpoGeral-->  
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div><!-- wrapper -->


        <script src="/template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="/template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="/template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="/template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="/template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="/template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		
	<!-- DATA TABES SCRIPT -->
		<script src="/template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="/template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="/template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="/template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="/template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="/template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="/template/bower_components/select2/dist/js/select2.min.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <!-- jQuery 3 -->
        <!-- <script src="template/bower_components/jquery/dist/jquery.min.js"></script> -->
        <!-- Bootstrap 3.3.7 -->
        <!-- <script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script> -->
        <!-- iCheck -->
        <!-- <script src="template/plugins/iCheck/icheck.min.js"></script> -->

        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->
        <!-- daterangepicker -->
        <script src="/template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="/template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
        <script>
        $('.select2').select2();

        /**
        * Plugin datepicker
        * Ativa o datepicker e traduz
        * @type {String}
        */
        
        // $.fn.datepicker.defaults.format = 'dd-mm-yyyy';
        // $.fn.datepicker.defaults.dayNames = ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
        // $.fn.datepicker.defaults.dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];


        $('#txt_date').datepicker({
            dateFormat: 'dd-mm-yy',
            dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
            dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
            dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
            monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
            monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
            nextText: 'Próximo',
            prevText: 'Anterior',
            autoclose: true
        });

        <?php if($user_type == 3 || $user_type == 4) //echo('$("#div_admin").hide();');?>
       
            function tratarValor(campo){
                var valor = $('#'+campo).val();

                valor = valor.replace('.', ',');
                var p = valor.indexOf(",");
                if((valor.length-p) == 3 && p != -1){
                    valor = valor.replace(',', '');
                }
                else if((valor.length-p) == 2){
                    valor + '0';
                    valor = valor.replace(',', '');
                    valor = valor * 10;
                }
                else{
                    valor = valor * 100;
                }
                $('#'+campo+'2').val(valor);

            }

            function revisaCampos(){
                if($("#opt_commission").val() == '2'){
                    $("#div_data").show();
                }
                else{
                    $("#div_data").hide();
                }
                
                if($('#txt_corporate').val() == '' || 
                $('#txt_value_contract').val() == '' || 
                $('#opt_commission').val() == '' ||
                $('#txt_indentification').val() == '' ||
                $('#txt_value_commission2').val() == ''){
                    $("#btn_cadastrar").attr("disabled","true");    
                }
                else{
                    $("#btn_cadastrar").removeAttr("disabled","false");    
                }
            }

            $(function () {
                $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' /* optional */
                });
            });
            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                 ?>
                 
			});

            $("#txt_cep").focusout(function(){//API viacep
                $.ajax({
                    type: 'POST',
                    url: 'apiViaCEP',
                    dataType: 'json',
                    data: 'id='+$("#txt_cep").val(),
                    success: function(resposta){
                        $("#txt_rua").val(resposta.logradouro);
                        $("#txt_complemento").val(resposta.complemento);
                        $("#txt_bairro").val(resposta.bairro);
                        $("#txt_cidade").val(resposta.localidade);
                        $("#opt_estado_name").val(resposta.uf);
                        $('#opt_estado_name').trigger('change');
                    }
                });
            });
        </script>	
    </body>
</html>