<?php
    
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
    $uuid = isset($uuid) ? $uuid : '';
    $contracts = isset($contracts) ? $contracts : '';//uuids dos contratos
    $validate = isset($message['validate']) ? $message['validate'] : '';//mensagem do validador dos campos
    $user_type = $_SESSION['user']['user_type'];//tipo de usuario
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Editar Contratos</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="/template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="/template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="/template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/template/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="/template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="/template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link rel="stylesheet" href="/template/bower_components/select2/dist/css/select2.min.css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script>
		   // $('.select2').select2();
	    </script>
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        <div class="wrapper">

            <?php include_once(__DIR__.'/../header.phtml'); ?>
            
            <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Contratos
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Editar Contratos</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                            

                                        <form id="myForm" class="form-horizontal" action="../editaContrato" method="post">
                                            <div class="box-body">
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Contratos:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_contract_uuid' name="contract_uuid" class="normal form-control select2" onchange="carregaContrato();">
                                                            <option value="">Selecione um Contrato</option>
                                                            <?php
                                                                foreach($contracts as $value){
                                                                    echo("<option value='".$value["uuid"]."'>".$value["corporate_name"]."</option>");
                                                                }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">Nome da Empresa:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_corporate_name" name="corporate_name" placeholder="corporate_name" onkeyup="revisaCampos();">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Valor:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_value2" name="value2" placeholder="00,00" onkeyup="revisaCampos();tratarValor($('#txt_value2').val());">
                                                        <input type="hidden" class="form-control" id="txt_value" name="value">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Data:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_date" name="date" placeholder="00/00/0000" onkeyup="revisaCampos();">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Nr. Identificação:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_indentification" name="indentification" placeholder="Identificação" onkeyup="revisaCampos();">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Observação:</label>
                                                    <div class="col-sm-6">
                                                        <textarea class="form-control" id="txa_observation" name="observation"></textarea>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-sm-3 col-sm-offset-2">
                                                        <button id="editar" type="submit" class="btn btn-primary" onclick="" disabled="true">Editar</button>
                                                    </div>
                                                </div>
                                            </div>    
                                        </form>
                                    </div>
                                </div><!--box-body-->
                            </div>
                        </div>    
                    </div><!--row-->    
                </section> <!--content-->   
            </div><!--corpoGeral-->  
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div><!-- wrapper -->


        <script src="/template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="/template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="/template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="/template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="/template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="/template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		
	<!-- DATA TABES SCRIPT -->
		<script src="/template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="/template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="/template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="/template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="/template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="/template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="/template/bower_components/select2/dist/js/select2.min.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <!-- jQuery 3 -->
        <!-- <script src="template/bower_components/jquery/dist/jquery.min.js"></script> -->
        <!-- Bootstrap 3.3.7 -->
        <!-- <script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script> -->
        <!-- iCheck -->
        <!-- <script src="template/plugins/iCheck/icheck.min.js"></script> -->

        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->
        <!-- daterangepicker -->
        <script src="/template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="/template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
        <script>
        $('.select2').select2();

        $('#txt_date').datepicker({
            dateFormat: 'dd-mm-yy',
            dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
            dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
            dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
            monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
            monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
            nextText: 'Próximo',
            prevText: 'Anterior',
            autoclose: true
        });
       
            function tratarValor(valor){
                valor = valor.replace('.', ',');
                var p = valor.indexOf(",");
                if((valor.length-p) == 3 && p != -1){
                    valor = valor.replace(',', '');
                }
                else{
                    valor = valor * 100;
                }
                $("#txt_value").val(valor);

            }

            function carregaContrato(){
                var uuid = $('#opt_contract_uuid').val();
                $.ajax({
                    type: 'POST',
                    url: '/carregaEditarContrato',
                    data: 'uuid='+uuid,
                    dataType: 'json',
                    success: function (dados) {
                        $('#txt_corporate_name').val(dados['corporate_name']);
                        
                        var ano  = dados['date'].split("-")[0];
                        var mes  = dados['date'].split("-")[1];
                        var dia  = dados['date'].split("-")[2];

                        data = dia + '/' + (mes) + '/' + (ano); 

                        $('#txt_date').val(dia + '/' + (mes) + '/' + (ano));
                        $('#txt_indentification').val(dados['indentification']);
                        $('#txa_observation').html(dados['observation']);
                        
                        var value = dados['value'];
                        if(value.length < 3 && value.length == 2){
                            value = '0'+value;
                        }
                        else if(value.length < 3 && value.length == 1){
                            value = '00' + value;
                        }
                        
                        var final = value.substring(value.length - 2, value.length);
                        value = value.substring(0,value.length - 2);
                        $('#txt_value').val(dados['value']);
                        $('#txt_value2').val(value+','+final);

                        revisaCampos();

                       
                    },
                    error: function (dados){
                        toastr.error('Erro ao carregar o Contrato');
                    }
                });
            }

            function revisaCampos(){
                if($('#txt_corporate_name').val() == '' || 
                $('#txt_value').val() == '' || 
                $('#txt_date').val() == '' ||
                $('#txa_observation').val() == '' ||
                $('#txt_indentification').val() == ''){
                    $("#editar").attr("disabled","true");    
                }
                else{
                    $("#editar").removeAttr("disabled","false");    
                }
            }

            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }

                var uuid = '<?php echo($uuid); ?>';
                if(uuid != ''){
                    $('#opt_contract_uuid').val(uuid);
                    $('#opt_contract_uuid').trigger('change');
                }

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                 ?>
			});
        </script>	
    </body>
</html>