<?php
    
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
    //$users  = isset($users) ? $users : '';//uuids dos usuarios
    $validate = isset($message['validate']) ? $message['validate'] : '';//mensagem do validador dos campos
    $user_type = $_SESSION['user']['user_type'];//tipo de usuario
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Lista Indicação</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="template/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link rel="stylesheet" href="template/bower_components/select2/dist/css/select2.min.css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script>
		   // $('.select2').select2();
	    </script>
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        <div class="wrapper">

            <?php include_once(__DIR__.'/../header.phtml'); ?>
            
            <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Contratos
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Listar Contratos</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                            

                                        <form id="myForm" class="form-horizontal" action="" method="get">
                                            <div class="box-body">
                                                <!-- <div class="form-group" id="div_user">
                                                    <label class="col-sm-2 control-label">Indicação:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_indication' name="indication" class="normal form-control select2" onchange="editarIndicacao($('#opt_user').val());">
                                                            <option value="">Selecione a Indicação</option>
                                                        </select> 
                                                    </div>    
                                                </div> -->
                                                <div class="form-group" id="div_busca">
                                                    <label class="col-sm-2 control-label">Tipo de busca:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_busca' name="busca" class="normal form-control select2" onchange="
                                                            if($('#opt_busca').val() == 1){
                                                                $('#div_corporate_name').show();
                                                                $('#div_observation').hide();
                                                                $('#div_indentification').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 2){
                                                                $('#div_indentification').show();
                                                                $('#div_corporate_name').hide();
                                                                $('#div_observation').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 3){
                                                                $('#div_observation').show();
                                                                $('#div_corporate_name').hide();
                                                                $('#div_indentification').hide();
                                                            }
                                                            else{
                                                                $('#div_observation').hide();
                                                                $('#div_corporate_name').hide();
                                                                $('#div_nome_responsavel').hide();
                                                                $('#div_indentification').hide();
                                                            }
                                                        ">
                                                            <option value="">Selecione o tipo de busca</option>
                                                            <option value="1">Nome Empresa</option>
                                                            <option value="2">Nr. Identificação</option>
                                                            <option value="3">Observação</option>
                                                        </select>
                                                    </div>    
                                                </div>
                                                <div class="form-group" id="div_observation" style="display:none">
                                                    <label class="col-sm-2 control-label">Observação:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_observation" name="observation" placeholder="Observação" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_corporate_name" style="display:none">
                                                    <label class="col-sm-2 control-label">Nome Empresa:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_corporate_name" name="corporate_name" placeholder="Nome Empresa" onkeyup="
                                                            // var cpf = document.getElementById('txt_corporate_name').value;
                                                            // cpf = cpf.replace(/\D+/g, '');
                                                            // document.getElementById('txt_corporate_name').value = cpf;
                                                            //atualizaUsuario('cpf',$('#txt_cpf').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_indentification" style="display:none">
                                                    <label class="col-sm-2 control-label">Nr. Identificação:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_indentification" name="indentification" placeholder="Identificação" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                </div>
                                                

                                                <div class="form-group">
                                                    <div class="col-sm-3 col-sm-offset-2">
                                                        <button id="buscar" type="button" class="btn btn-primary" onclick="listaContratos()">Buscar</button>
                                                    </div>
                                                </div>
                                            </div>    
                                        </form>
                                    </div>
                                </div><!--box-body-->
                            </div>
                        </div>    
                    </div><!--row-->    

                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Lista de Contratos</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-sm-12 col-xs-6">
                                            <div class="description-block">
                                                <div id="div_lista">
                                                    <div class="table-responsive">
                                                        <div id="id_tabela" style="max-height: 500px;overflow-y: auto;">
                                                            <table id="tbUsuario" class="table table-bordered table-striped">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Comissões</th>
                                                                        <th width="300">Nome Empresa</th>
                                                                        <th>Valor</th>
                                                                        <th>Data</th>
                                                                        <th width="300">Nome Consultor</th>
                                                                        <th>Nr. Identificação</th>
                                                                        <th>Observação</th>
                                                                       
                                                                        <?php if($user_type != 4){?>
                                                                            <th width="10"><i class="fa fa-edit"></i></th>
                                                                        <?php }?>
                                                                    </tr>
                                                                </thead>
                                                                <tbody  id="tbIndicacaoBody">

                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>	
                                                </div><!-- Fim his_buscas -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->

                    <!-- MODAL VER COMISSÕES-->
                    <div class="modal fade" id="modal_commission" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">Comissões</h4>
                            </div>
                            <div class="modal-body">
                            <table id='table_commissions' class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Valor</th>
                                        <th>Data</th>
                                        <th>Status</th>
                                        <th>Observação</th>
                                        <th width="10"><i class="fa fa-edit"></i></th>
                                    </tr>
                                </thead>
                                <tbody id="tbody_commission">
                                
                                </tbody>
                            </table>

                            </div>
                        </div>
                    </div>
                    </div>


                </section> <!--content-->   
            </div><!--corpoGeral-->  
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div><!-- wrapper -->


        <script src="template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		<!-- daterangepicker -->
		<script src="template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
		<script src="template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="template/bower_components/select2/dist/js/select2.min.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <!-- jQuery 3 -->
        <!-- <script src="template/bower_components/jquery/dist/jquery.min.js"></script> -->
        <!-- Bootstrap 3.3.7 -->
        <!-- <script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script> -->
        <!-- iCheck -->
        <!-- <script src="template/plugins/iCheck/icheck.min.js"></script> -->

        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->

        <script>
        $('.select2').select2();

            function listaContratos(){
                var dia = '';
                var mes = '';
                var ano = '';
                var data = '';
                var tabela = '';
                var status = '';
                var nome = '';
                var valor = '';
                var comissao = '';
                var consultor= '';

                if($('#opt_busca').val() == ''){
                    toastr.warning('Digite um valor para a busca');
                    return false;
                }

                if($('#opt_busca').val() == 1){
                    if($('#txt_corporate_name').val() == ''){
                        toastr.warning('Digite um valor para a busca');
                        return false;
                    }
                    var nome = 'nome=corporate_name';
                    var valor = '&valor='+$('#txt_corporate_name').val();
                }
                else if($('#opt_busca').val() == 2){
                    if($('#txt_indentification').val() == ''){
                        toastr.warning('Digite um valor para a busca');
                        return false;
                    }
                    var nome = 'nome=indentification';
                    var valor = '&valor='+$('#txt_indentification').val();
                }
                else if($('#opt_busca').val() == 3){
                    if($('#txt_observation').val() == ''){
                        toastr.warning('Digite um valor para a busca');
                        return false;
                    }
                    var nome = 'nome=observation';
                    var valor = '&valor='+$('#txt_observation').val();
                }
                

                $.ajax({
                    type: 'POST',
                    url: 'filtroContratoLista',
                    dataType: 'json',
                    data: nome+valor,
                    success: function(resposta){
                        var dia = '';
                        var mes = '';
                        var ano = '';
                        var data = '';
                        for(var i=0; i<resposta.length;i++){
     
                            ano  = resposta[i]['date'].split("-")[0];
                            mes  = resposta[i]['date'].split("-")[1];
                            dia  = resposta[i]['date'].split("-")[2];

                            data = dia + '/' + (mes) + '/' + (ano);                

                            tabela += '<tr>';
                            tabela += '<td><button class="btn btn-default btn-xs" onclick="ver_comisao(\''+resposta[i]['indication_uuid']+'\');"><i class="fa fa-eye"></i></button></td>';
                            tabela += '<td>'+resposta[i]['corporate_name']+'</td>';
                            tabela += '<td>R$'+(resposta[i]['value']/100)+'</td>';
                            tabela += '<td>'+data+'</td>';
                            tabela += '<td>'+resposta[i]['consultor']+'</td>';
                            tabela += '<td>'+resposta[i]['indentification']+'</td>';
                            tabela += '<td>'+resposta[i]['observation']+'</td>';
                            
                            <?php if($user_type != 4){?>
                                tabela += '<td><button onclick="editarContrato(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                            <?php }?>
                            tabela += '</tr>';
                        }
                        $('#tbIndicacaoBody').html(tabela);
                    }
                });
            }

            function ver_comisao(uuid){
                $('#tbody_commission').html('');
                $.get('getCommissionsIndication/'+uuid,function(data){
                    var resposta = JSON.parse(data);
                    var data = new Date();
                    var mes_atual = data.getMonth()+1;
                    var ano_atual = data.getFullYear();

                    var tabela = "";
                    var status = "";
                    var dia = '';
                    var mes = '';
                    var ano = '';
                    var data = '';
                    var observation = '';
                    var botao = '';
                    for(var i=0; i<resposta.length;i++){

                        ano  = resposta[i]['date'].split("-")[0];
                        mes  = resposta[i]['date'].split("-")[1];
                        dia  = resposta[i]['date'].split("-")[2];

                        

                        if(mes_atual == mes && ano_atual == ano)    data = "-> "+dia + '/' + (mes) + '/' + (ano);
                        else                                        data = dia + '/' + (mes) + '/' + (ano);

                        if(resposta[i]['observation'] == null)  observation = "<td></td>";
                        else                                    observation = "<td>"+resposta[i]['observation']+"</td>";
                        
                        botao = '';
                        <?php if($user_type != 4){?>
                            if(resposta[i]['paid'] == 1)    botao = "<button onclick='payCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>";
                            else                            botao = "<button onclick='unpaidCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>";
                        <?php }?>

                        if(resposta[i]['paid'] == 1)    status = "<td style='color:red' id=pay"+i+">Não Pago "+botao+"</td>";
                        else                            status = "<td style='color:green' id=pay"+i+">Pago "+botao+"</td>";
                            
                        tabela += "<tr>";
                        tabela += '<td>R$'+(resposta[i]['value_commission']/100)+'</td>';
                        tabela += '<td>'+data+'</td>';
                        tabela += status;
                        tabela += observation;
                        tabela += '<td><button onclick="editarComissao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                        tabela += '</tr>';

                    }
                    $('#tbody_commission').html(tabela);
                });
                
                $('#modal_commission').modal();
            }

            function editarContrato(uuid){
                $("#myForm").attr("action","editaContrato/"+uuid);    
                $("#myForm").submit();
            }

            function editarComissao(uuid){
                $("#myForm").attr("action","editaComissao/"+uuid);    
                $("#myForm").submit();
            }

            function payCommission(uuid,i){
                var r = confirm("Deseja pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Pago <button onclick='unpaidCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>");
                            $('#pay'+i).css("color","green");
                        }
                        else{
                            toastr.error('Falha ao Pagar');    
                        }
                    });
                }
            }

            function unpaidCommission(uuid,i){
                var r = confirm("Deseja não pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Não Pago <button onclick='payCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>");
                            $('#pay'+i).css("color","red");
                        }
                        else{
                            toastr.error('Falha ao Não Pagar');    
                        }
                    });
                }
            }

            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                 ?>
			});
        </script>	
    </body>
</html>