<?php
    
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
    $uuid = isset($uuid) ? $uuid : '';
    $indications = isset($indications) ? $indications : '';//uuids das indicações
    $commissions = isset($commissions) ? $commissions : '';//uuids das indicações
    $validate = isset($message['validate']) ? $message['validate'] : '';//mensagem do validador dos campos
    $user_type = $_SESSION['user']['user_type'];//tipo de usuario
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Editar Comissão</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="/template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="/template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="/template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/template/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="/template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="/template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link rel="stylesheet" href="/template/bower_components/select2/dist/css/select2.min.css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script>
		   // $('.select2').select2();
	    </script>
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        <div class="wrapper">

            <?php include_once(__DIR__.'/../header.phtml'); ?>
            
            <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Comissão
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Editar Comissões</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                            

                                        <form id="myForm" class="form-horizontal" action="../editaComissao" method="post">
                                            <div class="box-body">
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Indicação:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_indication_uuid' name="indication_uuid" class="normal form-control select2" onchange="carregaComissaoIndicacao();">
                                                            <option value="">Selecione uma Indicação</option>
                                                            <?php
                                                                foreach($indications as $value){
                                                                    if($value["uuid"] == $indication_uuid)
                                                                        echo("<option value='".$value["uuid"]."' selected>".$value["name"]."</option>");
                                                                    else
                                                                        echo("<option value='".$value["uuid"]."'>".$value["name"]."</option>");
                                                                }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Comissões:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_commission_uuid' name="commission_uuid" class="normal form-control select2" onchange="carregaComissao();revisaCampos();">
                                                            <option value="">Selecione uma Comissao</option>
                                                            <?php
                                                                foreach($commissions as $value){
                                                                    echo("<option value='".$value["uuid"]."'>".$value["date"]." / R$".($value["value_commission"]/100)."</option>");
                                                                }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Valor:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_value2" name="value2" placeholder="00,00" onkeyup="revisaCampos();tratarValor($('#txt_value2').val());">
                                                        <input type="hidden" class="form-control" id="txt_value" name="value">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Data:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_date" name="date" placeholder="00/00/0000" onkeyup="revisaCampos();" readonly>
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Status</label>
                                                    <input type="hidden" class="form-control" id="txt_status" name="status">
                                                    <div class="col-sm-6" id="div_status">
                                                        
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Observação:</label>
                                                    <div class="col-sm-6">
                                                        <textarea class="form-control" id="txa_observation" name="observation"></textarea>
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Atualizar:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_update' name="update" class="normal form-control select2" onchange="revisaCampos();">
                                                            <option value="1">Atualizar apenas este lançamento</option>
                                                            <option value="2">Atualizar este e os próximos</option>
                                                            <option value="3">Atualizar todos os lançamentos</option>
                                                        </select>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-sm-3 col-sm-offset-2">
                                                        <button id="editar" type="submit" class="btn btn-primary" onclick="" disabled="true">Editar</button>
                                                    </div>
                                                </div>
                                            </div>    
                                        </form>
                                    </div>
                                </div><!--box-body-->
                            </div>
                        </div>    
                    </div><!--row-->    
                </section> <!--content-->   
            </div><!--corpoGeral-->  
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div><!-- wrapper -->


        <script src="/template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="/template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="/template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="/template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="/template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="/template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		
	<!-- DATA TABES SCRIPT -->
		<script src="/template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="/template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="/template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="/template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="/template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="/template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="/template/bower_components/select2/dist/js/select2.min.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <!-- jQuery 3 -->
        <!-- <script src="template/bower_components/jquery/dist/jquery.min.js"></script> -->
        <!-- Bootstrap 3.3.7 -->
        <!-- <script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script> -->
        <!-- iCheck -->
        <!-- <script src="template/plugins/iCheck/icheck.min.js"></script> -->

        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->
        <!-- daterangepicker -->
        <script src="/template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="/template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
        <script>
        $('.select2').select2();

       
       
            function tratarValor(valor){
                valor = valor.replace('.', ',');
                var p = valor.indexOf(",");
                if((valor.length-p) == 3 && p != -1){
                    valor = valor.replace(',', '');
                }
                else{
                    valor = valor * 100;
                }
                $("#txt_value").val(valor);

            }

            function carregaComissao(){
                var uuid = $('#opt_commission_uuid').val();
                if(uuid){
                    $.ajax({
                        type: 'POST',
                        url: '/carregaEditarComissao',
                        data: 'uuid='+uuid,
                        dataType: 'json',
                        success: function (dados) {
                            
                            var ano  = dados['date'].split("-")[0];
                            var mes  = dados['date'].split("-")[1];
                            var dia  = dados['date'].split("-")[2];

                            data = dia + '/' + (mes) + '/' + (ano); 

                            var paid = "";
                            if(dados['paid'] == 2){
                                $('#txt_status').val(2);
                                paid = "<p style='color:green'>Pago <button onclick='unpaidCommission(\""+uuid+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button></p>";
                            }
                            else{
                                $('#txt_status').val(1);
                                paid = "<p style='color:red'>Não Pago <button onclick='payCommission(\""+uuid+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button></p>";
                            }

                            $('#txt_date').val(dia + '/' + (mes) + '/' + (ano));
                            $('#div_status').html(paid);
                            $('#txa_observation').html(dados['observation']);
                            
                            var value = dados['value_commission'];
                            if(value.length < 3 && value.length == 2){
                                value = '0'+value;
                            }
                            else if(value.length < 3 && value.length == 1){
                                value = '00' + value;
                            }
                            
                            var final = value.substring(value.length - 2, value.length);
                            value = value.substring(0,value.length - 2);
                            $('#txt_value').val(dados['value_commission']);
                            $('#txt_value2').val(value+','+final);

                            revisaCampos();
                        },
                        error: function (dados){
                            toastr.error('Erro ao carregar a Comissão');
                        }
                    });
                    revisaCampos();
                }
            }

            function carregaComissaoIndicacao(){
                var uuid = $('#opt_indication_uuid').val();
                if(uuid){
                    $.ajax({
                        type: 'POST',
                        url: '/carregaEditarComissaoIndicacao',
                        data: 'uuid='+uuid,
                        dataType: 'json',
                        async: false,
                        success: function (dados) {
                            var dia = "";
                            var mes = "";
                            var ano = "";
                            var campos = "<option value='' selected>Selecione uma Comissão</option>";
                            for(var i=0;i<dados.length;i++){

                                ano  = dados[i]['date'].split("-")[0];
                                mes  = dados[i]['date'].split("-")[1];
                                dia  = dados[i]['date'].split("-")[2];

                                campos += "<option value="+dados[i]['uuid']+">"+dia + '/' + (mes) + '/' + (ano)+" / "+(dados[i]['value_commission']/100)+"</option>";
                            }
                            $('#opt_commission_uuid').html(campos);
                            $('#opt_commission_uuid').trigger('change');

                            revisaCampos();
                        },
                        error: function (dados){
                            toastr.error('Erro ao carregar a Comissão');
                        }
                    });
                }
                else{
                    toastr.warning('Selecione uma indicação');
                }
            }

            function payCommission(uuid){
                var r = confirm("Deseja pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#txt_status').val(2);
                            $('#div_status').html("<p style='color:green'>Pago <button onclick='unpaidCommission(\""+uuid+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button></p>");
                        }
                        else{
                            toastr.error('Falha ao Pagar');    
                        }
                    });
                }
            }

            function unpaidCommission(uuid){
                var r = confirm("Deseja não pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#txt_status').val(1);
                            $('#div_status').html("<p style='color: red;'>Não Pago <button onclick='payCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>");
                        }
                        else{
                            toastr.error('Falha ao Não Pagar');    
                        }
                    });
                }
            }

            function revisaCampos(){
                if($('#txt_corporate_name').val() == '' || 
                $('#txt_value').val() == '' || 
                $('#txt_date').val() == '' ||
                $('#txt_indentification').val() == ''){
                    $("#editar").attr("disabled","true");    
                }
                else{
                    $("#editar").removeAttr("disabled","false");    
                }
            }

            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }

                var uuid = '<?php echo($uuid); ?>';
                if(uuid != ''){
                    $('#opt_commission_uuid').val(uuid);
                    $('#opt_commission_uuid').trigger('change');
                }

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                 ?>
			});
        </script>	
    </body>
</html>