<?php
    
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
    //$users  = isset($users) ? $users : '';//uuids dos usuarios
    $validate = isset($message['validate']) ? $message['validate'] : '';//mensagem do validador dos campos
    $user_type = $_SESSION['user']['user_type'];//tipo de usuario
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Lista Indicação</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="template/dist/css/AdminLTE.min.css">
        <!-- Data Table -->
        <link rel="stylesheet" href="/template/bower_components/datatables.net-bs/css/dataTables.bootstrap.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link rel="stylesheet" href="template/bower_components/select2/dist/css/select2.min.css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script>
		   // $('.select2').select2();
	    </script>
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        <div class="wrapper">

            <?php include_once(__DIR__.'/../header.phtml'); ?>
            
            <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Bônus
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Listar Bônus</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                            

                                        <form id="myForm" class="form-horizontal" action="" method="get">
                                            <div class="box-body">
                                                <!-- <div class="form-group" id="div_user">
                                                    <label class="col-sm-2 control-label">Indicação:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_indication' name="indication" class="normal form-control select2" onchange="editarIndicacao($('#opt_user').val());">
                                                            <option value="">Selecione a Indicação</option>
                                                        </select> 
                                                    </div>    
                                                </div> -->
                                                <div style="margin:10px;">
                                                    <div class="form-group"> 
                                                        <div class="col-sm-2">
                                                            <input type="text" class="form-control" name="nr_contrato" id="txt_nr_contrato" placeholder="Nr. contrato">	
                                                        </div>

                                                        <div class="col-sm-2">
                                                            <input type="text" class="form-control" name="valor" id="txt_valor" placeholder="Valor Comissão">	
                                                        </div>

                                                        <div class="col-sm-4">
                                                            <input type="text" class="form-control" name="responsavel" id="txt_responsavel" placeholder="Nome responsavel">	
                                                        </div>

                                                        <div class="col-sm-4">
                                                            <input type="text" class="form-control" name="indicador" id="txt_indicador" placeholder="Criador da indicação">	
                                                        </div>                               
                                                    </div>

                                                    <div class="form-group"> 
                                                        <div class="col-sm-2">
                                                            <select class="form-control" id="mes">
                                                                <option value="escolha">Mês</option>
                                                                <option value="01">(01) Janeiro</option><option value="02">(02) Fevereiro</option><option value="03">(03) Março</option><option value="04">(04) Abril</option><option value="05">(05) Maio</option><option value="06">(06) Junho</option><option value="07">(07) Julho</option><option value="08">(08) Agosto</option><option value="09">(09) Setembro</option><option value="10">(10) Outubro</option><option value="11">(11) Novembro</option><option value="12">(12) Dezembro</option>							  			</select>
                                                        </div>

                                                        <div class="col-sm-2">
                                                            <select class="form-control" id="ano">
                                                                <option value="escolha">Ano</option>
                                                                <option value="2020">2020</option><option value="2019">2019</option><option value="2018">2018</option>							  			</select>
                                                        </div>

                                                        <div class="col-sm-4">
                                                            <input type="text" class="form-control" name="empresa" id="txt_empresa" placeholder="Empresa Contrato">	
                                                        </div>   

                                                        <div class="col-sm-2">            
                                                            <select class="form-control" name="status" id="status">
                                                                <option value="">Todas</option>
                                                                <option value="1" <?php if($_SESSION['user']['user_type'] == 1 || $_SESSION['user']['user_type'] == 2) echo"selected";?>>Não Pagas</option>
                                                                <option value="2">Pagas</option>
                                                            </select>
                                                        </div>

                                                        <div class="col-sm-2">    
                                                            <label class="col-sm-10 control-label">Meus Bônus:</label>
                                                            <input type="checkbox" style="width:20px;" value="1" name="meus_bonus" id="chk_meus_bonus" class="checkbox_check" checked>
                                                        </div>                 
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="col-sm-1">
                                                            <button id="buscar" type="button" class="btn btn-primary" onclick="listaComissoes()">Buscar</button>
                                                        </div>
                                                    </div>
                                                </div>
                                                  
                                                

                                                
                                            </div>    

                                    </div>
                                </div><!--box-body-->
                            </div>
                        </div>    
                    </div><!--row-->    

                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Lista de Bônus</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-sm-12 col-xs-6">
                                            
                                                <div id="div_lista">
                                                    <div class="table-responsive">
                                                        <div id="id_tabela" style="max-height: 500px;overflow-y: auto;">
                                                            <table id="tbIndicacao" class="table table-bordered table-striped">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Status</th>
                                                                        <th>Valor</th>
                                                                        <th>Data</th>
                                                                        <th>Descrição</th>
                                                                        <th width="300">Nome Recebedor</th>
                                                                       
                                                                        <?php if($user_type != 4){?>
                                                                            <th width="10"><i class="fa fa-edit"></i></th>
                                                                            <th width="10"><i class="fa fa-trash-o"></i></th>
                                                                        <?php }?>
                                                                    </tr>
                                                                </thead>
                                                                <tbody  id="tbIndicacaoBody">

                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>	
                                                </div><!-- Fim his_buscas -->
                                            
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->


                    <!-- MODAL VER COMISSÕES-->
                    <div class="modal fade" id="modal_commission" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">Bônus</h4>
                            </div>
                            <div class="modal-body">
                            <table id='table_commissions' class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Valor</th>
                                        <th>Data</th>
                                        <th>Status</th>
                                        <th>Observação</th>
                                        <th width="10"><i class="fa fa-edit"></i></th>
                                        <th width="10"><i class="fa fa-trash-o"></i></th>
                                    </tr>
                                </thead>
                                <tbody id="tbody_commission">
                                
                                </tbody>
                            </table>

                            </div>
                        </div>
                    </div>
                    </div>


                </section> <!--content-->   
            </div><!--corpoGeral-->  
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div><!-- wrapper -->


        <script src="template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		<!-- daterangepicker -->
		<script src="template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
		<script src="template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="template/bower_components/select2/dist/js/select2.min.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <!-- jQuery 3 -->
        <!-- <script src="template/bower_components/jquery/dist/jquery.min.js"></script> -->
        <!-- Bootstrap 3.3.7 -->
        <!-- <script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script> -->
        <!-- iCheck -->
        <!-- <script src="template/plugins/iCheck/icheck.min.js"></script> -->

        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->

        <script>
        $('.select2').select2();
        listaComissoes();

            // function atualizaUsuario(nome,valor){
            //     $.ajax({
            //         type: 'POST',
            //         url: 'filtroUserLista',
            //         dataType: 'json',
            //         data: 'nome='+nome+'&valor='+valor,
            //         success: function(resposta){
            //             $('#opt_user').empty();
            //             $("#opt_user").append(new Option('Selecione um usuário', ''));
            //             for(var i=0; i<resposta.length;i++){
            //                 $("#opt_user").append(new Option(resposta[i]['name'], resposta[i]['uuid']));
            //             }
            //         }
            //     });
            // }

            function listaComissoes(){
                var tabela = '';
                var status = '';
                var nome = '';
                var valor = '';
                var comissao = '';
                var consultor= '';
                var join = '';
                
                if ($('input.checkbox_check').is(':checked')) {
                    var my_commission = true;
                }
                else{
                    var my_commission = false;
                }

                $.ajax({
                    type: 'POST',
                    url: 'filtroComissaoLista',
                    dataType: 'json',
                    data: "nr_contrato="+$('#txt_nr_contrato').val()+
                    "&valor="+$('#txt_valor').val()+
                    "&responsavel="+$('#txt_responsavel').val()+
                    "&indicador="+$('#txt_indicador').val()+
                    "&mes="+$('#mes').val()+
                    "&ano="+$('#ano').val()+
                    "&empresa="+$('#txt_empresa').val()+
                    "&my_commission="+my_commission+
                    "&status="+$('#status').val(),
                    success: function(resposta){
                        var t = $('#tbIndicacao').dataTable();t.fnDestroy();
                        for(var i=0; i<resposta.length;i++){
                            
                            botao = '';
                            <?php if($user_type == 1 || $user_type == 2){?>
                                if(resposta[i]['paid'] == 1)    botao = "<button onclick='payCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>";
                                else                            botao = "<button onclick='unpaidCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>";
                            <?php }?>

                            
                            if(resposta[i]['paid'] == 1)    status = "<td style='color:red' id=pay"+i+">Não Pago "+botao+"</td>";
                            else                            status = "<td style='color:green' id=pay"+i+">Pago "+botao+"</td>";
                            
                            
                            
                            if(!resposta[i]['observation']){
                                observacao = " ";
                            }
                            else{
                                observacao = resposta[i]['observation'];
                            }

                            tabela += '<tr id="'+i+'">';
                            tabela += status+'</td>';
                            tabela += '<td>R$'+(resposta[i]['value']/100)+'</td>';
                            tabela += '<td>'+resposta[i]['date']+'</td>';
                            tabela += '<td>'+observacao+'</td>';
                            tabela += '<td>'+resposta[i]['name']+'</td>';//criador

                            <?php if($user_type == 1 || $user_type == 2){?>
                                tabela += '<td><button onclick="editarComissao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                                tabela += '<td><button onclick="excluirComissao(\''+resposta[i]['uuid']+'\',\''+i+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-trash-o"></i></button></td>';
                            <?php }?>
                            tabela += '</tr>';
                        }
                        $('#tbIndicacaoBody').html(tabela);

                        
                        $('#tbIndicacao').DataTable({
                            'autoWidth'   : true,
                            'aLengthMenu' :	[[10, 25, 50, -1], [10, 25, 50, "Tudo"]],
                            'oLanguage'   : {"sEmptyTable": "Nenhum registro encontrado", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando 0 até 0 de 0 registros", "sInfoFiltered": "(Filtrados de _MAX_ registros)", "sInfoPostFix": "", "sInfoThousands": ".", "sLengthMenu": "_MENU_ resultados por página", "sLoadingRecords": "Carregando...", "sProcessing": "Processando...", "sZeroRecords": "Nenhum registro encontrado", "sSearch": "Pesquisar", "oPaginate": { "sNext": "Próximo", "sPrevious": "Anterior", "sFirst": "Primeiro", "sLast": "Último" }, "oAria": { "sSortAscending": ": Ordenar colunas de forma ascendente", "sSortDescending": ": Ordenar colunas de forma descendente"}}
                        });
                    }
                });
            }

            function editarComissao(uuid){
                $("#myForm").attr("action","editaComissao/"+uuid);    
                $("#myForm").submit();
            }

            function excluirComissao(uuid,num){
                if(confirm("Deseja deletar a comissão?")){
                    $.ajax({
                    type: 'POST',
                    url: '/excluiComissao',
                    dataType: 'json',
                    data: 'uuid='+uuid,
                    success: function(resposta){

                        
                        if(resposta){
                            $("#"+num+"").remove();
                            toastr.success('Deletado');
                        }
                    }
                    
                    });
                }
            }

            function payCommission(uuid,i){
                var r = confirm("Deseja pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Pago <button onclick='unpaidCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>");
                            $('#pay'+i).css("color","green");
                        }
                        else{
                            toastr.error('Falha ao Pagar');    
                        }
                    });
                }
            }

            function unpaidCommission(uuid,i){
                var r = confirm("Deseja não pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Não Pago <button onclick='payCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>");
                            $('#pay'+i).css("color","red");
                        }
                        else{
                            toastr.error('Falha ao Não Pagar');    
                        }
                    });
                }
            }

            function editarIndicacao(uuid){
                $("#myForm").attr("action","editaIndicacao/"+uuid);    
                $("#myForm").submit();
            }

            function excluirIndicacao(uuid,num){
                if(confirm("Deseja deletar a indicação?")){
                    $.ajax({
                    type: 'POST',
                    url: 'excluiIndicacao',
                    dataType: 'json',
                    data: 'uuid='+uuid,
                    success: function(resposta){
                        if(resposta){
                            $("#"+num+"").remove();
                            toastr.success('Deletado');
                        }
                    }
                    
                    });
                }
            }

            function carregaIndicadores(){
                $.get('getCreators',function(data){
                    var opcoes = "<option value=''>Escolha um Indicador</option>";
                    var data = JSON.parse(data);
                    for(var i=0; i<data.length;i++){
                        opcoes += "<option value='"+data[i]['uuid']+"'>"+data[i]['name']+"</option>"; 
                    }
                    $('#opt_creator').html(opcoes);
                });
            }

            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
                
                // $.ajax({
                //     type: 'POST',
                //     url: 'filtroIndicacaoLista',
                //     dataType: 'json',
                //     data: 'nome=email&valor=@',
                //     success: function(resposta){
                //         $('#opt_indication').empty();
                //         $("#opt_indication").append(new Option('Selecione uma Indicação', ''));
                //         for(var i=0; i<resposta.length;i++){
                //             $("#opt_indication").append(new Option(resposta[i]['name'], resposta[i]['uuid']));
                //         }
                //     }
                // });
                

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                 ?>
			});
        </script>	
    </body>
</html>