<?php
    set_time_limit(false);
	// error_reporting(E_ALL);
	// ini_set('display_errors',1);
	// ini_set('html_errors',1);
    $error = isset($message['error']) ? $message['error'] : '';
    $validate = isset($message['validate']) ? $message['validate'] : '';
    $success = isset($message['success']) ? $message['success'] : '';
?>
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Adicionar Compania</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="template/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">

        <div class="wrapper">

        <?php include_once(__DIR__.'/../header.phtml'); ?>
        
        <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Compania
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Adicionar Compania</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                                        <form id="myForm" class="form-horizontal" action="cadastroCompania" method="post">
                                            <div class="box-body">

                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">Nome:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="normal form-control" id="txt_name" name="name" placeholder="Nome" onkeyup="revisaCampos();">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">CNPJ:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="normal form-control" id="txt_cnpj" name="cnpj" placeholder="CNPJ" onchange="
                                                            var cnpj = document.getElementById('txt_cnpj').value;
                                                            cnpj = cnpj.replace(/\D+/g, '');
                                                            document.getElementById('txt_cnpj').value = cnpj;
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-sm-3 col-sm-offset-2">
                                                        <button id="cadastrar" type="submit" class="btn btn-primary" disabled="true">Cadastrar</button>
                                                    </div>
                                                </div>
                                            </div>	
                                        </form>
                                    </div>
                                </div>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->
                </section>
            </div>
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div>        

        <script src="template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		<!-- daterangepicker -->
		<script src="template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
		<script src="template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="template/bower_components/select2/dist/js/select2.full.min.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	

        <script>

            function revisaCampos(){
                if($('#txt_name').val() == '' || 
                $('#txt_cnpj').val() == '' ){
                    $("#cadastrar").attr("disabled","true");    
                }
                else{
                    $("#cadastrar").removeAttr("disabled","false");    
                }
            }

            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                ?>
			});
        </script>	
    </body>
</html>