<?php
    $user_type = $_SESSION['user']['user_type'];
    $validate = isset($message['validate']) ? $message['validate'] : '';
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
?>
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Log in</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="/template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="/template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="/template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/template/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="/template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="/template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        
    <div class="wrapper">

            <?php include_once(__DIR__.'/header.phtml'); ?>
            
            <?php include_once(__DIR__.'/nav_menu.phtml'); ?>

        <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">
            <section class="content-header">
                <h1>
                Home
                    <small></small>
                </h1>
                <ol class="breadcrumb">
                    <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                    <li><i class="fa fa-dashboard"></i> Home</li>
                </ol>
            </section>	
            
            <section class="content">
                <!-- Info boxes -->
                <div class="row">
                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_indicacoes" style="display:none;" name="div_row">
                    <div class="info-box" name="info_box">
                        <span class="info-box-icon bg-yellow"><i class="ion ion-clipboard"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text"><?php if($user_type == 1 || $user_type == 2) echo('Indicações Sem <br>Cunsultor');
                                                    else echo('Indicações <br>Pendentes'); ?></span>
                        <span class="info-box-number" id="span_pendentes">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->

                    <!-- fix for small devices only -->
                    <div class="clearfix visible-sm-block"></div>

                   
                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_usuarios_pendentes" style="display:none;" name="div_row">
                    <div class="info-box" name="info_box">
                        <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Usuários<br> Pendentes</span>
                        <span class="info-box-number" id="span_usuarios">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->

                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_indicacoes2" name="div_row2">
                    <div class="info-box" name="info_box">
                        <span class="info-box-icon bg-blue"><i class="ion ion-clipboard"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Minhas <br>Indicações</span>
                        <span class="info-box-number" id="span_indicacoes">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->


                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_minhas_indicacoes" name="div_row2" style="display:none;">
                    <div class="info-box" name="info_box">
                        <span class="info-box-icon bg-yellow"><i class="ion ion-clipboard"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Indicações <br>Pendentes</span>
                        <span class="info-box-number" id="span_minhas_pendentes">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->

                    
                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_fechados2" name="div_row2" style="display:none;">
                    <div class="info-box" name="info_box">
                        <span class="info-box-icon bg-green"><i class="fa fa-handshake-o"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Negócios <br>Ganhos</span>
                        <span class="info-box-number" id="span_ganhos2">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->


                    <!-- fix for small devices only -->
                    <div class="clearfix visible-sm-block"></div>


                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_comissao2" name="div_row2">
                    <div class="info-box" name="info_box">
                        <span class="info-box-icon bg-green"><i class="fa fa-money"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Comissão de<br> Indicações</span>
                        <span class="info-box-number" id="span_comissao">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->

                </div>
                <!-- /.row -->

                

                <div class="row" id="rowIndicationsPendent">
                    <div class="col-md-12"> 
                    <div class="box box-info">
                        <div class="box-header with-border">
                        <h3 class="box-title">Indicações Pendentes</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                
                                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <form id="myForm" class="form-horizontal" action="" method="get">
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-sm-12 col-xs-6">
                                        <div class="description-block">
                                            <div class="table-responsive">
                                                <div id="id_tabela" style="max-height: 500px;overflow-y: auto;">
                                                    <table id="tbIndicacao" class="table table-bordered table-striped">
                                                        <thead>
                                                            <tr>
                                                            <th width="300">Nome</th>
                                                                <th>CPF_CNPJ</th>
                                                                <th>Telefone</th>
                                                                <th width="300">Nome Responsável</th>
                                                                <th>Email</th>
                                                                <th>Status</th> 
                                                                <th>Comissao</th>  
                                                                <th>Consultor</th>
                                                                
                                                                <?php if($user_type != 4){?>
                                                                    <th width="10"><i class="fa fa-edit"></i></th>
                                                                <?php }?>   
                                                            </tr>
                                                        </thead>
                                                        <tbody  id="tbIndicacoesBody">

                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>   	
                                        </div>
                                    </div>
                                </div>
                            <!-- /.row -->
                            </div>
                        </form>    
                        <!-- ./box-body -->
                        <div class="box-footer">
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-sm-3 col-xs-6">
                                    <div class="description-block">
                                        <div id="total_indicacoes"><h5 class="description-header">1200</h5></div>
                                        <span class="description-text">Total</span>
                                    </div>
                                <!-- /.description-block -->
                                </div>
                            </div>
                        <!-- /.row -->
                        </div>
                        <!-- /.box-footer -->
                    </div>
                    <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->

                <div class="row" style="display:none;" id="row_user">
                    <div class="col-md-12"> 
                    <div class="box box-info">
                        <div class="box-header with-border">
                        <h3 class="box-title">Usuários Pendentes</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                
                                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <form id="myForm2" class="form-horizontal" action="" method="get">
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-sm-12 col-xs-6">
                                        <div class="description-block">
                                            <div class="table-responsive">
                                                <div style="max-height: 500px;overflow-y: auto;">
                                                    <table id="tbUsuario" class="table table-bordered table-striped">
                                                        <thead>
                                                            <tr>
                                                            <th width="300">Nome</th>
                                                                <th>Email</th>
                                                                <th>CPF</th>
                                                                <th>Tipo</th>
                                                                <th>Status</th>
                                                                <?php if($user_type != 4){?>
                                                                    <th width="10"><i class="fa fa-edit"></i></th>
                                                                <?php }?>   
                                                            </tr>
                                                        </thead>
                                                        <tbody  id="tbUsuarioBody">

                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>	
                                        </div>
                                    </div>
                                </div>
                            <!-- /.row -->
                            </div>
                        </form>    
                        <!-- ./box-body -->
                        <div class="box-footer">
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-sm-3 col-xs-6">
                                    <div class="description-block">
                                        <div id="total_usuarios"><h5 class="description-header"></h5>0</div>
                                        <span class="description-text">Total</span>
                                    </div>
                                <!-- /.description-block -->
                                </div>
                            </div>
                        <!-- /.row -->
                        </div>
                        <!-- /.box-footer -->
                    </div>
                    <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
                
                <div class="row" id="rowMyIndicationsCharts">
                    <div class="col-md-12"> 
                    <div class="box box-info">
                        <div class="box-header with-border">
                        <h3 class="box-title">Minhas Indicações</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                
                                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <form id="myForm3" class="form-horizontal" action="" method="get">
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-sm-12 col-xs-6">
                                        <div class="description-block">
                                            <div class="table-responsive">
                                                <div id="id_tabela" style="max-height: 500px;overflow-y: auto;">
                                                    <table id="tbIndicacao" class="table table-bordered table-striped">
                                                        <thead>
                                                            <tr>
                                                                <th>Comissões</th>
                                                                <th width="300">Nome</th>
                                                                <th>CPF_CNPJ</th>
                                                                <th>Telefone</th>
                                                                <th width="300">Nome Responsável</th>
                                                                <th>Email</th>
                                                                <th>Status</th> 
                                                                <th>Comissao</th>  
                                                                <th>Consultor</th>
                                                                
                                                                <?php if($user_type != 4){?>
                                                                    <th width="10"><i class="fa fa-edit"></i></th>
                                                                <?php }?>   
                                                            </tr>
                                                        </thead>
                                                        <tbody  id="tbMyIndicationsBody">

                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>   	
                                        </div>
                                    </div>
                                </div>
                            <!-- /.row -->
                            </div>
                        </form>    
                        <!-- ./box-body -->
                        <div class="box-footer">
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-sm-3 col-xs-6">
                                    <div class="description-block">
                                        <div id="total_my_indications"><h5 class="description-header">0</h5></div>
                                        <span class="description-text">Total</span>
                                    </div>
                                <!-- /.description-block -->
                                </div>
                            </div>
                        <!-- /.row -->
                        </div>
                        <!-- /.box-footer -->
                    </div>
                    <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->



                <div class="row" id="rowMyIndications">
                    <div class="col-md-12"> 
                    <div class="box box-info">
                        <div class="box-header with-border">
                        <h3 class="box-title">Indicações</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                
                                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="chart">
                                <!-- <canvas id="barChart" style="height: 100px; width: 489px;" height="100" width="489"></canvas> -->
                                <div id="IndicationsChart"></div>
                            </div>
                        </div>
                       
                    </div>
                    <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->

                <!-- MODAL VER COMISSÕES-->
                <div class="modal fade" id="modal_commission" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Comissões</h4>
                        </div>
                        <div class="modal-body">
                        <table id='table_commissions' class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Valor</th>
                                    <th>Data</th>
                                    <th>Status</th>
                                    <th>Observação</th>
                                    <th width="10"><i class="fa fa-edit"></i></th>
                                </tr>
                            </thead>
                            <tbody id="tbody_commission">
                            
                            </tbody>
                        </table>

                        </div>
                    </div>
                </div>
                </div>


                <div class="row" id="rowMyIndicationsCharts">
                    <div class="col-md-12"> 
                    <div class="box box-info">
                        <div class="box-header with-border">
                        <h3 class="box-title">Minhas Indicações</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                
                                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="chart">
                                <!-- <canvas id="barChart" style="height: 100px; width: 489px;" height="100" width="489"></canvas> -->
                                <div id="myIndicationsChart"></div>
                            </div>
                        </div>
                       
                    </div>
                    <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
              
            </section>

    </div>
        
            <!-- <h2>Hello <?= $_SESSION["user"]["name"]; ?>!</h2> -->

        <?php include_once(__DIR__.'/footer.phtml'); ?>
        </div>    

        <script src="/template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="/template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="/template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="/template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="/template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="/template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		<!-- daterangepicker -->
		<script src="/template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="/template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
		<script src="/template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="/template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="/template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="/template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="/template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.bundle.min.js"></script>
		<script src="/template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="/template/bower_components/select2/dist/js/select2.full.min.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

        <script>
            $(document).ready(function() {
    
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                    if($message == "success")
                        echo "toastr.success('".$message."');";
                    else if($message == "error")
                        echo "toastr.error('".$message."');";    
                        
                 ?>

                var user_type = '<?php echo $user_type;?>';
                var uuid = '<?php echo $_SESSION['user']['id'];?>';
                var tabela = '';
                var status = '';
                var status2 = '';
                var nome = '';
                var valor = '';
                var comissao = '';
                var consultor= '';
                var ganhos = 0;
                var perdidos = 0;
                var usuarios = 0;
                var pendentes = 0;
                var total = 0;
                var andamento = 0;
                var filtro = '&filtro=ORDER BY indications.status';

                // if(user_type == 1 || user_type == 2){
                //     $('[name ="info_box"]').css("width", "100%");
                //     $('[name ="div_row"]').css("width", "20%");
                // }
                

                //$('#div_comissao').show();
                if(user_type != 4){
                //     nome = 'nome=creator_uuid';
                //     valor = '&valor='+uuid;
                //     var status = '';
                //     $('#div_comissao').show();
                    $('#div_indicacoes').show();  
                    $('#div_fechados').show();  
                    $('#div_perdidos').show();  
                    $('#div_comissao').show();
                }
                if(user_type == 3){
                    nome = 'nome=user_uuid';
                    valor = '&valor='+uuid;
                    status2 = 1;
                }
                else if(user_type == 2){
                    var status = 'status=7';
                    status2 = 7;
                }
                else if(user_type == 1){
                    nome = 'nome=email';
                    valor = '&valor=@';
                    status2 = 7;
                    $('#div_usuarios_pendentes').show();
                }
                var t = 0;
                if(user_type == 4){
                    $('#rowIndicationsPendent').hide();
                    $('#rowMyIndications').hide();
                    $('#div_fechados2').show();
                    $('#div_minhas_indicacoes').show();
                }
                
                else{
                    $.ajax({// carrega a tabela de indicações pendentes
                        type: 'POST',
                        async:false,
                        url: '/filtroIndicacaoLista',
                        dataType: 'json',
                        data: nome+valor+status+filtro,
                        success: function(resposta){
                            t = resposta.length;
                            if(resposta.length < 1){
                                tabela="<tr><td>Nenhuma Indicação Encontrada</td></tr>";
                                $('#tbUsuarioBody').html(tabela);
                            }
                            else{
                                for(var i=0; i<resposta.length;i++){

                                    if(resposta[i]['status'] == 5)  ganhos++;
                                    else if(resposta[i]['status'] == 6)  perdidos++;
                                    else if(resposta[i]['status'] != 7) andamento++;
                                    if(resposta[i]['status'] == status2){

                                        if(resposta[i]['status'] == 1){ status = "<td style='color:orange'><b>Atribuída</b>"; pendentes++;}
                                        else if(resposta[i]['status'] == 2) status = "<td><b>Cliente contatado</b>";
                                        else if(resposta[i]['status'] == 3) status = "<td><b>Visita Realizada</b>"; 
                                        else if(resposta[i]['status'] == 4) status = "<td><b>Proposta Enviada</b>"; 
                                        else if(resposta[i]['status'] == 5) status = "<td style='color:green'><b>Negócio ganho</b>"; 
                                        else if(resposta[i]['status'] == 6) status = "<td style='color:red'><b>Negócio perdido</b>";
                                        else if(resposta[i]['status'] == 7){ status = "<td style='color:red'><b>Sem Consultor</b>"; pendentes++;}
                                        else status = "<td style='color:red'><b>Cancelado</b>";
                                        
                                        if(resposta[i]['commission'] == 1)   comissao = "<td>Fixa";
                                        else                                 comissao = "<td>Recorrente";
                                        
                                        if(resposta[i]['user_uuid'] == null)   consultor = "<td>Sem Consultor";
                                        else                                 consultor = "<td>"+resposta[i]['user_name'];

                                        tabela += '<tr>';
                                        tabela += '<td>'+resposta[i]['name']+'</td>';
                                        tabela += '<td>'+resposta[i]['cpf_cnpj']+'</td>';
                                        tabela += '<td>'+resposta[i]['telefone']+'</td>';
                                        tabela += '<td>'+resposta[i]['name_responsavel']+'</td>';
                                        tabela += '<td>'+resposta[i]['email']+'</td>';
                                        tabela += status+'</td>';
                                        tabela += comissao+'</td>';
                                        tabela += consultor+'</td>';

                                        <?php if($user_type != 4){?>
                                            tabela += '<td><button onclick="editarIndicacao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                                        <?php }?>
                                        tabela += '</tr>';
                                        total++
                                    }
                                }
                                $('#tbIndicacoesBody').html(tabela);
                                $('#total_indicacoes').html(total);
                                $('#span_pendentes').html(pendentes);

                            }
                        }
                    });
                }

                // carrega a tabela de usuarios pendentes
                if(user_type == 1 || user_type == 2){
                    var tabela2 = '';
                    var status = '';
                    var tipo = '';
                    nome = '';
                    valor = '';
                    var total2 = 0;

                    status = 'status=2';

                    $.ajax({
                        type: 'POST',
                        async:false,
                        url: '/filtroUserLista',
                        dataType: 'json',
                        data: status,
                        success: function(resposta){
                            if(resposta.length < 1){
                                tabela2="<tr><td>Nenhum Usuário encontrado</td></tr>";
                                $('#tbUsuarioBody').html(tabela2);
                            }
                            else{
                                for(var i=0; i<resposta.length;i++){
                                    if(resposta[i]['status'] == 1) status = "<td style='color:green'><b>Ativado</b>";
                                    else if(resposta[i]['status'] == 2) status = "<td style='color:orange'><b>Pendente</b>";
                                    else status = "<td style='color:red'><b>Desativado</b>";
                                    
                                    if(resposta[i]['user_type'] == 1) tipo = "Super";
                                    else if(resposta[i]['user_type'] == 2) tipo = "Admin";
                                    else if(resposta[i]['user_type'] == 3) tipo = "Consultor";
                                    else tipo = "Usuário";

                                    tabela2 += '<tr>';
                                    tabela2 += '<td>'+resposta[i]['name']+'</td>';
                                    tabela2 += '<td>'+resposta[i]['email']+'</td>';
                                    tabela2 += '<td>'+resposta[i]['cpf']+'</td>';
                                    tabela2 += '<td>'+tipo+'</td>';
                                    tabela2 += status+'</td>';
                                    <?php if($user_type == 1 || $user_type == 2){?>
                                        tabela2 += '<td><button onclick="editarUsuario(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                                    <?php }?>
                                    tabela2 += '</tr>';
                                    total2++;
                                }
                                
                                $('#tbUsuarioBody').html(tabela2);
                                $('#total_usuarios').html(total2);
                                $('#span_usuarios').html(total2);
                            }    
                        }
                    });
                    $('#row_user').show();

                    
                }

                //carrega a tabela minhas indicações
                nome = 'nome=creator_uuid';
                valor = '&valor='+uuid;
                var status = '';
                var tabela3 = "";
                var total3 = "";
                var ganhos2 = 0;
                var perdidos2 = 0;
                var pendentes2 = 0;
                var andamento2 = 0;
                var commission = 0;
                $.ajax({
                    type: 'POST',
                    async:false,
                    url: '/filtroIndicacaoLista',
                    dataType: 'json',
                    data: nome+valor+status+filtro,
                    success: function(resposta){
                        if(resposta.length < 1){
                            tabela3="<tr><td>Nenhuma Indicação Encontrada</td></tr>";
                            $('#tbMyIndicationsBody').html(tabela3);
                        }
                        else{
                            for(var i=0; i<resposta.length;i++){
                                commission += parseInt(resposta[i]['value_commission']);
                                // if(resposta[i]['status'] == 5)  ganhos2++;
                                // else if(resposta[i]['status'] == 6)  perdidos2++;
                                // else if(resposta[i]['status'] != 7) andamento2++;
                                if(resposta[i]['status'] == 1){ status = "<td style='color:orange'><b>Atribuída</b>"; pendentes2++;}
                                else if(resposta[i]['status'] == 2) {status = "<td><b>Cliente contatado</b>";pendentes2++;}
                                else if(resposta[i]['status'] == 3) {status = "<td><b>Visita Realizada</b>";pendentes2++;}
                                else if(resposta[i]['status'] == 4) {status = "<td><b>Proposta Enviada</b>";pendentes2++;}
                                else if(resposta[i]['status'] == 5) {status = "<td style='color:green'><b>Negócio ganho</b>"; ganhos2++;}
                                else if(resposta[i]['status'] == 6) {status = "<td style='color:red'><b>Negócio perdido</b>"; perdidos2++;}
                                else if(resposta[i]['status'] == 7){ status = "<td style='color:red'><b>Sem Consultor</b>"; pendentes2++;}
                                else status = "<td style='color:red'><b>Cancelado</b>";
                                
                                if(resposta[i]['commission'] == 1)   comissao = "<td>Fixa";
                                else                                 comissao = "<td>Recorrente";
                                
                                if(resposta[i]['user_uuid'] == null)   consultor = "<td>Sem Consultor";
                                else                                 consultor = "<td>"+resposta[i]['user_name'];

                                tabela3 += '<tr>';
                                tabela3 += '<td><button type="button" class="btn btn-default btn-xs" onclick="ver_comisao(\''+resposta[i]['uuid']+'\');"><i class="fa fa-eye"></i></button></td>';
                                tabela3 += '<td>'+resposta[i]['name']+'</td>';
                                tabela3 += '<td>'+resposta[i]['cpf_cnpj']+'</td>';
                                tabela3 += '<td>'+resposta[i]['telefone']+'</td>';
                                tabela3 += '<td>'+resposta[i]['name_responsavel']+'</td>';
                                tabela3 += '<td>'+resposta[i]['email']+'</td>';
                                tabela3 += status+'</td>';
                                tabela3 += comissao+'</td>';
                                tabela3 += consultor+'</td>';

                                <?php if($user_type != 4){?>
                                    tabela3 += '<td><button onclick="editarIndicacao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                                <?php }?>
                                tabela3 += '</tr>';
                                total3++
                            }
                            
                            $('#tbMyIndicationsBody').html(tabela3);
                            $('#total_my_indications').html(total3);
                            //if(user_type == 4){
                                $('#span_indicacoes').html(total3);
                                $('#span_ganhos2').html(ganhos2);
                                $('#span_minhas_pendentes').html(pendentes2);
                        }


                        commission = String(commission);
                        if(commission.length < 3 && commission.length == 2){
                            commission = '0'+commission;
                        }
                        else if(commission.length < 3 && commission.length == 1){
                            commission = '00' + commission;
                        }
                        
                        var final = commission.substring(commission.length - 2, commission.length);
                        commission = commission.substring(0,commission.length - 2);

                        $('#span_comissao').html('R$'+commission+','+final);
                        //}
                    }
                });

            

                //Charts
                //Indicações
                if(user_type != 4){
                    var d = [t, pendentes, andamento, ganhos, perdidos];

                    Highcharts.setOptions({
                        colors: ['#3f7fbf', '#f3e744', '#f28a13', '#6ff344', '#f01417']
                    });

                    chart = Highcharts.chart('IndicationsChart', {
                        chart : {
                            renderTo : 'IndicationsChart',
                            //backgroundColor : '#00000',
                            type : 'column',
                        },
                        title : {
                            text : 'Indicações'
                        },
                        credits : {
                            enabled : false
                        },
                        legend : {
                            layout : 'vertical',
                            align : 'right',
                            verticalAlign : 'top',
                            floating: true,
                            //backgroundColor : '#CCC',
                            x : 0,
                            y : 40,
                            borderWidth : 0,
                            itemStyle : {
                                color : '#000',
                                fontSize: "9px"
                            }
                        },
                        yAxis : {
                            min : 0,
                            title : {
                                text : 'Quantidade'
                            }
                        },
                        xAxis : {
                            categories : ['Indicações', 'Atribuídas', 'Em Andamento', 'Ganhas', 'Perdidas']
                        },
                        plotOptions: {
                                column: {
                                    pointPadding: 0.2,
                                    borderWidth: 0,
                                    dataLabels: {
                                        enabled: true,
                                        //rotation: -45,
                                        color: '#000',
                                        align: 'center',
                                        style: {
                                            fontSize: "15px"
                                        },
                                        x: 5,
                                        y: 5
                                    }
                                }
                            },
                        series : []
                    });
                    chart.addSeries({
                        name : ['Indicações'],
                        data : [d[0]],
                    });
                    chart.addSeries({
                        name : ['Atribuídas'],
                        data : [d[1]],
                    });
                    chart.addSeries({
                        name : ['Em Andamento'],
                        data : [d[2]],
                    });
                    chart.addSeries({
                        name : ['Ganhas'],
                        data : [d[3]],
                    });
                    chart.addSeries({
                        name : ['Perdidas'],
                        data : [d[4]],
                    });
                }

                //myIndicationsCharts
                var d = [total3, pendentes2, ganhos2, perdidos2];

                Highcharts.setOptions({
                    colors: ['#3f7fbf', '#f3e744', '#6ff344', '#f01417']
                });

                chart = Highcharts.chart('myIndicationsChart', {
		            chart : {
                        renderTo : 'myIndicationsChart',
                        //backgroundColor : '#00000',
                        type : 'column',
                    },
                    title : {
                        text : 'Minhas Indicações'
                    },
                    credits : {
                        enabled : false
                    },
                    legend : {
                        layout : 'vertical',
                        align : 'right',
                        verticalAlign : 'top',
                        floating: true,
                        //backgroundColor : '#CCC',
                        x : 0,
                        y : 40,
                        borderWidth : 0,
                        itemStyle : {
                            color : '#000',
                            fontSize: "9px"
                        }
                    },
                    yAxis : {
                        min : 0,
                        title : {
                            text : 'Quantidade'
                        }
                    },
                    xAxis : {
                        categories : ['Indicações', 'Pendentes', 'Ganhas', 'Perdidas']
                    },
                    plotOptions: {
                            column: {
                                pointPadding: 0.2,
                                borderWidth: 0,
                                dataLabels: {
                                    enabled: true,
                                    //rotation: -45,
                                    color: '#000',
                                    align: 'center',
                                    style: {
                                        fontSize: "15px"
                                    },
                                    x: 5,
                                    y: 5
                                }
                            }
                        },
                    series : []
                });
                chart.addSeries({
					name : ['Indicações'],
					data : [d[0]],
				});
                chart.addSeries({
					name : ['Pendentes'],
					data : [d[1]],
				});
                chart.addSeries({
					name : ['Ganhas'],
					data : [d[2]],
				});
                chart.addSeries({
					name : ['Perdidas'],
					data : [d[3]],
				});
      
			});

            function editarComissao(uuid){
                $("#myForm").attr("action","editaComissao/"+uuid);    
                $("#myForm").submit();
            }

            function payCommission(uuid,i){
                var r = confirm("Deseja pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Pago <button onclick='unpaidCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>");
                            $('#pay'+i).css("color","green");
                        }
                        else{
                            toastr.error('Falha ao Pagar');    
                        }
                    });
                }
            }

            function unpaidCommission(uuid,i){
                var r = confirm("Deseja não pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Não Pago <button onclick='payCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>");
                            $('#pay'+i).css("color","red");
                        }
                        else{
                            toastr.error('Falha ao Não Pagar');    
                        }
                    });
                }
            }

            function ver_comisao(uuid){
                $('#tbody_commission').html('');
                $.get('getCommissionsIndication/'+uuid,function(data){
                    var resposta = JSON.parse(data);
                    var data = new Date();
                    var mes_atual = data.getMonth()+1;
                    var ano_atual = data.getFullYear();

                    var tabela = "";
                    var status = "";
                    var dia = '';
                    var mes = '';
                    var ano = '';
                    var data = '';
                    var observation = '';
                    var botao = '';
                    for(var i=0; i<resposta.length;i++){

                        ano  = resposta[i]['date'].split("-")[0];
                        mes  = resposta[i]['date'].split("-")[1];
                        dia  = resposta[i]['date'].split("-")[2];

                        

                        if(mes_atual == mes && ano_atual == ano)    data = "-> "+dia + '/' + (mes) + '/' + (ano);
                        else                                        data = dia + '/' + (mes) + '/' + (ano);

                        if(resposta[i]['observation'] == null)  observation = "<td></td>";
                        else                                    observation = "<td>"+resposta[i]['observation']+"</td>";
                        
                        botao = '';
                        <?php if($user_type != 4){?>
                            if(resposta[i]['paid'] == 1)    botao = "<button onclick='payCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>";
                            else                            botao = "<button onclick='unpaidCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>";
                        <?php }?>

                        if(resposta[i]['paid'] == 1)    status = "<td style='color:red' id=pay"+i+">Não Pago "+botao+"</td>";
                        else                            status = "<td style='color:green' id=pay"+i+">Pago "+botao+"</td>";
                            
                        tabela += "<tr>";
                        tabela += '<td>R$'+(resposta[i]['value_commission']/100)+'</td>';
                        tabela += '<td>'+data+'</td>';
                        tabela += status;
                        tabela += observation;
                        tabela += '<td><button onclick="editarComissao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                        tabela += '</tr>';

                    }
                    $('#tbody_commission').html(tabela);
                });
                
                $('#modal_commission').modal();
            }

            function editarIndicacao(uuid){
                $("#myForm").attr("action","editaIndicacao/"+uuid);    
                $("#myForm").submit();
            }

            function editarUsuario(uuid){
                $("#myForm2").attr("action","editaLogin/"+uuid);    
                $("#myForm2").submit();
            }
        </script>
    </body>
</html>
