<?php
    $user_type = $_SESSION['user']['user_type'];
?>
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Log in</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="template/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        
    <div class="wrapper">

            <?php include_once(__DIR__.'/header.phtml'); ?>
            
            <?php include_once(__DIR__.'/nav_menu.phtml'); ?>

        <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">
            <section class="content-header">
                <h1>
                Home
                    <small></small>
                </h1>
                <ol class="breadcrumb">
                    <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                    <li><i class="fa fa-dashboard"></i> Home</li>
                </ol>
            </section>	
            
            <section class="content">
                <!-- Info boxes -->
                <div class="row">
                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_indicacoes">
                    <div class="info-box">
                        <span class="info-box-icon bg-yellow"><i class="ion ion-clipboard"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Indicações <br>Pendentes</span>
                        <span class="info-box-number" id="span_pendentes">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_fechados">
                    <div class="info-box">
                        <span class="info-box-icon bg-green"><i class="fa fa-handshake-o"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Negócios<br> Ganhos</span>
                        <span class="info-box-number" id="span_ganhos">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->

                    <!-- fix for small devices only -->
                    <div class="clearfix visible-sm-block"></div>

                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_perdidos">
                    <div class="info-box">
                    
                        <span class="info-box-icon bg-red"><i class="fa fa-window-close"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Negócios<br>Perdidos</span>
                        <span class="info-box-number" id="span_perdidos">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_usuarios_pendentes" style="display:none;">
                    <div class="info-box">
                        <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Usuários<br> Pendentes</span>
                        <span class="info-box-number" id="span_usuarios">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-3 col-sm-6 col-xs-12" id="div_comissao" style="display:none;">
                    <div class="info-box">
                        <span class="info-box-icon bg-green"><i class="fa fa-money"></i></span>

                        <div class="info-box-content">
                        <span class="info-box-text">Comissão</span>
                        <span class="info-box-number" id="span_comissao">0</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->

                <div class="row">
                    <div class="col-md-12"> 
                    <div class="box box-info">
                        <div class="box-header with-border">
                        <h3 class="box-title">Indicações Pendentes</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                
                                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <form id="myForm" class="form-horizontal" action="" method="get">
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-sm-12 col-xs-6">
                                        <div class="description-block">
                                            <div class="table-responsive">
                                                <div id="id_tabela" style="max-height: 500px;overflow-y: auto;">
                                                    <table id="tbIndicacao" class="table table-bordered table-striped">
                                                        <thead>
                                                            <tr>
                                                            <th width="300">Nome</th>
                                                                <th>CPF_CNPJ</th>
                                                                <th>Telefone</th>
                                                                <th width="300">Nome Responsável</th>
                                                                <th>Email</th>
                                                                <th>Status</th> 
                                                                <th>Comissao</th>  
                                                                <th>Consultor</th>
                                                                
                                                                <?php if($user_type != 4){?>
                                                                    <th width="10"><i class="fa fa-edit"></i></th>
                                                                <?php }?>   
                                                            </tr>
                                                        </thead>
                                                        <tbody  id="tbIndicacoesBody">

                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>   	
                                        </div>
                                    </div>
                                </div>
                            <!-- /.row -->
                            </div>
                        </form>    
                        <!-- ./box-body -->
                        <div class="box-footer">
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-sm-3 col-xs-6">
                                    <div class="description-block">
                                        <div id="total_indicacoes"><h5 class="description-header">1200</h5></div>
                                        <span class="description-text">Total</span>
                                    </div>
                                <!-- /.description-block -->
                                </div>
                            </div>
                        <!-- /.row -->
                        </div>
                        <!-- /.box-footer -->
                    </div>
                    <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->

                <div class="row" style="display:none;" id="row_user">
                    <div class="col-md-12"> 
                    <div class="box box-info">
                        <div class="box-header with-border">
                        <h3 class="box-title">Usuários Pendentes</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                
                                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <form id="myForm2" class="form-horizontal" action="" method="get">
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-sm-12 col-xs-6">
                                        <div class="description-block">
                                            <div class="table-responsive">
                                                <div style="max-height: 500px;overflow-y: auto;">
                                                    <table id="tbUsuario" class="table table-bordered table-striped">
                                                        <thead>
                                                            <tr>
                                                            <th width="300">Nome</th>
                                                                <th>Email</th>
                                                                <th>CPF</th>
                                                                <th>Tipo</th>
                                                                <th>Status</th>
                                                                <?php if($user_type != 4){?>
                                                                    <th width="10"><i class="fa fa-edit"></i></th>
                                                                <?php }?>   
                                                            </tr>
                                                        </thead>
                                                        <tbody  id="tbUsuarioBody">

                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>	
                                        </div>
                                    </div>
                                </div>
                            <!-- /.row -->
                            </div>
                        </form>    
                        <!-- ./box-body -->
                        <div class="box-footer">
                            <div class="row">
                                <!-- /.col -->
                                <div class="col-sm-3 col-xs-6">
                                    <div class="description-block">
                                        <div id="total_usuarios"><h5 class="description-header"></h5></div>
                                        <span class="description-text">Total</span>
                                    </div>
                                <!-- /.description-block -->
                                </div>
                            </div>
                        <!-- /.row -->
                        </div>
                        <!-- /.box-footer -->
                    </div>
                    <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
                
              
            </section>

    </div>
        
            <!-- <h2>Hello <?= $_SESSION["user"]["name"]; ?>!</h2> -->

        <?php include_once(__DIR__.'/footer.phtml'); ?>
        </div>    

        <script src="template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		<!-- daterangepicker -->
		<script src="template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
		<script src="template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="template/bower_components/select2/dist/js/select2.full.min.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

        <script>
            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
                var user_type = '<?php echo $user_type;?>';
                var uuid = '<?php echo $_SESSION['user']['id'];?>';
                var tabela = '';
                var status = '';
                var status2 = '';
                var nome = '';
                var valor = '';
                var comissao = '';
                var consultor= '';
                var ganhos = 0;
                var perdidos = 0;
                var usuarios = 0;
                var pendentes = 0;
                var total = 0;
                var filtro = '&filtro=ORDER BY indications.status';


                if(user_type == 4){
                    nome = 'nome=creator_uuid';
                    valor = '&valor='+uuid;
                    var status = '';
                    $('#div_comissao').show();
                }
                else if(user_type == 3){
                    nome = 'nome=user_uuid';
                    valor = '&valor='+uuid;
                    status2 = 1;
                }
                else if(user_type == 2){
                    var status = 'status=7';
                }
                else if(user_type == 1){
                    nome = 'nome=email';
                    valor = '&valor=@';
                    status2 = 7;
                    $('#div_usuarios_pendentes').show();
                }
                
                $.ajax({//tabela de indicações
                    type: 'POST',
                    url: 'filtroIndicacaoLista',
                    dataType: 'json',
                    data: nome+valor+status+filtro,
                    success: function(resposta){
                        if(resposta.length < 1) toastr.warning('Nenhuma indicação pendente!');
                        for(var i=0; i<resposta.length;i++){

                            if(resposta[i]['status'] == 5)  ganhos++;
                            if(resposta[i]['status'] == 6)  perdidos++;
                            if(resposta[i]['status'] == status2 || user_type == 4){

                                if(resposta[i]['status'] == 1){ status = "<td style='color:orange'><b>Pendente</b>"; pendentes++;}
                                else if(resposta[i]['status'] == 2) status = "<td><b>Cliente contatado</b>";
                                else if(resposta[i]['status'] == 3) status = "<td><b>Visita Realizada</b>";
                                else if(resposta[i]['status'] == 4) status = "<td><b>Proposta Enviada</b>";
                                else if(resposta[i]['status'] == 5) status = "<td style='color:green'><b>Negócio ganho</b>";
                                else if(resposta[i]['status'] == 6) status = "<td style='color:red'><b>Negócio perdido</b>";
                                else if(resposta[i]['status'] == 7){ status = "<td style='color:red'><b>Sem Consultor</b>"; pendentes++;}
                                else status = "<td style='color:red'><b>Cancelado</b>";
                                
                                if(resposta[i]['commission'] == 1)   comissao = "<td>Fixa";
                                else                                 comissao = "<td>Recorrente";
                                
                                if(resposta[i]['user_uuid'] == '')   consultor = "<td>Sem Consultor";
                                else                                 consultor = "<td>"+resposta[i]['user_name'];

                                tabela += '<tr>';
                                tabela += '<td>'+resposta[i]['name']+'</td>';
                                tabela += '<td>'+resposta[i]['cpf_cnpj']+'</td>';
                                tabela += '<td>'+resposta[i]['telefone']+'</td>';
                                tabela += '<td>'+resposta[i]['name_responsavel']+'</td>';
                                tabela += '<td>'+resposta[i]['email']+'</td>';
                                tabela += status+'</td>';
                                tabela += comissao+'</td>';
                                tabela += consultor+'</td>';

                                <?php if($user_type != 4){?>
                                    tabela += '<td><button onclick="editarIndicacao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                                <?php }?>
                                tabela += '</tr>';
                                total++
                            }
                        }
                        $('#tbIndicacoesBody').html(tabela);
                        $('#total_indicacoes').html(total);
                        $('#span_pendentes').html(pendentes);
                        $('#span_ganhos').html(ganhos);
                        $('#span_perdidos').html(perdidos);
                    }
                });

                if(user_type == 1 || user_type == 2){
                    var tabela2 = '';
                    var status = '';
                    var tipo = '';
                    nome = '';
                    valor = '';
                    var total2 = 0;

                    status = 'status=2';

                    $.ajax({// tabela de usuarios
                        type: 'POST',
                        url: 'filtroUserLista',
                        dataType: 'json',
                        data: status,
                        success: function(resposta){
                            if(resposta.length < 1) toastr.warning('Nenhum usuário encontrado!');
                            else{
                                for(var i=0; i<resposta.length;i++){
                                    if(resposta[i]['status'] == 1) status = "<td style='color:green'><b>Ativado</b>";
                                    else if(resposta[i]['status'] == 2) status = "<td style='color:orange'><b>Pendente</b>";
                                    else status = "<td style='color:red'><b>Desativado</b>";
                                    
                                    if(resposta[i]['user_type'] == 1) tipo = "Super";
                                    else if(resposta[i]['user_type'] == 2) tipo = "Admin";
                                    else if(resposta[i]['user_type'] == 3) tipo = "Consultor";
                                    else tipo = "Usuário";

                                    tabela2 += '<tr>';
                                    tabela2 += '<td>'+resposta[i]['name']+'</td>';
                                    tabela2 += '<td>'+resposta[i]['email']+'</td>';
                                    tabela2 += '<td>'+resposta[i]['cpf']+'</td>';
                                    tabela2 += '<td>'+tipo+'</td>';
                                    tabela2 += status+'</td>';
                                    <?php if($user_type == 1 || $user_type == 2){?>
                                        tabela2 += '<td><button onclick="editarUsuario(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                                    <?php }?>
                                    tabela2 += '</tr>';
                                    total2++;
                                }
                                $('#tbUsuarioBody').html(tabela2);
                                $('#total_usuarios').html(total2);
                                $('#span_usuarios').html(total2);
                            }    
                        }
                    });
                    $('#row_user').show();
                }
			});

            function editarIndicacao(uuid){
                $("#myForm").attr("action","editaIndicacao/"+uuid);    
                $("#myForm").submit();
            }

            function editarUsuario(uuid){
                $("#myForm2").attr("action","editaLogin/"+uuid);    
                $("#myForm2").submit();
            }
        </script>
    </body>
</html>
