
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel" style="height: 35px;">
                <!-- <div class="pull-left image"> -->
                    <!-- <div class="img-circle" style="background:url('<?php //echo $imagemLogo; ?>') no-repeat center center; background-size:contain; width:45px; height:45px;"></div>-->
                    <!-- <img src='<?php //echo $imagemLogo; ?>' class="img-circle" alt="User Image" style="width: 100%;max-width: 40px;height: 40px;margin-left: 10px;"/>  -->
                    <!-- <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" /> -->
                <!-- </div> -->
                <div class="pull-left info">
                    <p><?php echo $_SESSION['user']['name']; ?></p>
                </div>
            </div>
            
            <ul class="sidebar-menu">
                <li class="header">Navegação Principal</li>

                <li >
                    <a href="/dashboard">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span> </i>
                    </a>
                </li>


                <!-- ## Section Logins / Empresas ## -->

                <?php if($_SESSION['user']['user_type'] != 4){?>
                <li class="treeview">
                    <a href="#"><i class="fa fa-users"></i><span>Usuários</span><i class="fa fa-angle-left pull-right"></i></a>
                    
                    <ul class="treeview-menu">
                        <li class="treeview">
                            <!-- <a href="#"><i class="fa fa-circle-o"></i>Usuário<i class="fa fa-angle-left pull-right"></i></a>
                
                            <ul class="treeview-menu"> -->
                                <li>
                                <a href="/cadastroLogin"><i class="fa fa-circle-o"></i>Adicionar</i></a>
                                    
                                </li>

                                <?php if($_SESSION['user']['user_type'] == 1 || $_SESSION['user']['user_type'] == 2){?>
                                    <li>
                                    <a href="/editaLogin"><i class="fa fa-circle-o"></i>Editar</i></a>             
                            
                                  
                                    </li>
                                <?php }?>
                                
                                <?php if($_SESSION['user']['user_type'] == 1 || $_SESSION['user']['user_type'] == 2){?>
                                <li>
                                    <a href="/listaUsers"><i class="fa fa-circle-o"></i>Listar</i></a>
                                    
                                </li>
                                <?php }?>
                            <!-- </ul> -->
                        </li>
<!-- 
                        <li class="treeview">
                            <a href="#"><i class="fa fa-circle-o"></i>Compania<i class="fa fa-angle-left pull-right"></i></a>
                
                            <ul class="treeview-menu">
                                <li>
                                <a href="/cadastroCompania"><i class="fa fa-circle-o"></i>Adicionar</i></a>
                                    
                                </li>

                                <?php if($_SESSION['user']['user_type'] == 1 || $_SESSION['user']['user_type'] == 2){?>
                                    <li>
                                    <a href="/editaCompania"><i class="fa fa-circle-o"></i>Editar</i></a>             
                                
                                    
                                    </li>
                                <?php }?>
                            </ul>
                        </li> -->


                    </ul>
                </li>
                <?php }?>

                <!-- Indicações -->
                <li class="treeview">
                    <a href="#"><i class="fa fa-handshake-o"></i><span>Indicacoes</span><i class="fa fa-angle-left pull-right"></i></a>
                
                    <ul class="treeview-menu">
                        <li class="treeview">
                            <li>
                                <a href="/cadastroIndicacao"><i class="fa fa-circle-o"></i>Adicionar</i></a>
                            </li>

                            <?php if($_SESSION['user']['user_type'] != 4){?>
                                <li>
                                    <a href="/editaIndicacao"><i class="fa fa-circle-o"></i>Editar</i></a>             
                                </li>
                            <?php }?>

                          
                                <li>
                                    <a href="/listaIndicacoes"><i class="fa fa-circle-o"></i>Listar</i></a>
                                    
                                </li>
                            
                        </li>    
                    </ul>
                </li>

                <!-- Contratos -->
                <?php if($_SESSION['user']['user_type'] != 4){?>
                <li class="treeview">
                    <a href="#"><i class="fa fa-file-text"></i><span>Contratos</span><i class="fa fa-angle-left pull-right"></i></a>
                
                    <ul class="treeview-menu">
                        <li class="treeview">
                            <?php if($_SESSION['user']['user_type'] != 4){?>
                                <li>
                                    <a href="/editaContrato"><i class="fa fa-circle-o"></i>Editar</i></a>             
                                </li>
                            <?php }?>

                            <?php if($_SESSION['user']['user_type'] != 4){?>
                                <li>
                                    <a href="/listaContratos"><i class="fa fa-circle-o"></i>Listar</i></a>
                                </li>
                            <?php }?>
                        </li>    
                    </ul>
                </li>
                <?php }?>

                <!-- Comissões -->
                <li class="treeview">
                    <a href="#"><i class="fa fa-money"></i><span>Bônus</span><i class="fa fa-angle-left pull-right"></i></a>
                
                    <ul class="treeview-menu">
                        <li class="treeview">
                            <?php if($_SESSION['user']['user_type'] == 1 || $_SESSION['user']['user_type'] == 2){?>
                                <li>
                                    <a href="/editaComissao"><i class="fa fa-circle-o"></i>Editar</i></a>             
                                </li>
                            <?php }?>

                            <li>
                                <a href="/listaComissoes"><i class="fa fa-circle-o"></i>Listar</i></a>
                                
                            </li>
                        </li>    
                    </ul>
                </li>
            </ul> <!-- ./ siderbar-menu -->


        </section>
        <!-- /.sidebar -->
    </aside>
    
    