<?php
    
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
    $companies = isset($companies) ? $companies : '';//uuids das companias
    $users = isset($users) ? $users : '';//uuids das companias
    $uuid = isset($uuid) ? $uuid : '';
    $indications = isset($indications) ? $indications : '';//uuids das indicações
    $validate = isset($message['validate']) ? $message['validate'] : '';//mensagem do validador dos campos
    $user_type = $_SESSION['user']['user_type'];//tipo de usuario
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Editar Indicação</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="/template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="/template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="/template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/template/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="/template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="/template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link rel="stylesheet" href="/template/bower_components/select2/dist/css/select2.min.css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script>
		   // $('.select2').select2();
	    </script>
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        <div class="wrapper">

            <?php include_once(__DIR__.'/../header.phtml'); ?>
            
            <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Indicação
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Editar Indicação</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                            

                                        <form id="myForm" class="form-horizontal" action="../editaIndicacao" method="post">
                                            <div class="box-body">
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Indicação:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_indication_uuid' name="indication_uuid" class="normal form-control select2" onchange="carregaIndicacao();">
                                                            <option value="">Selecione uma indicação</option>
                                                            <?php
                                                                foreach($indications as $value){
                                                                    echo("<option value='".$value["uuid"]."'>".$value["name"]."</option>");
                                                                }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">*Nome:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_name" name="name" placeholder="Nome" onkeyup="revisaCampos();" onchange="
                                                            if(this.value.length<6 || this.value.length>100){
                                                                toastr.error('O Nome deve ter de 6 à 100 caracteres!');
                                                                $('#txt_name').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_name').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">CPF_CNPJ:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_cpf_cnpj" name="cpf_cnpj" placeholder="CPF_CNPJ" onkeyup="revisaCampos();" onchange="
                                                            var cpf = document.getElementById('txt_cpf_cnpj').value;
                                                            cpf = cpf.replace(/\D+/g, '');
                                                            document.getElementById('txt_cpf_cnpj').value = cpf;
                                                            if((this.value.length<11 || this.value.length>14) && this.value){
                                                                toastr.error('O CPF_CNPJ deve ter de 11 à 14 números!');
                                                                $('#txt_cpf_cnpj').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_cpf_cnpj').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">*Telefone:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_telefone" name="telefone" placeholder="Telefone" onkeyup="revisaCampos();" onchange="
                                                            if(this.value.length<8 || this.value.length>20){
                                                                toastr.error('O Telefone deve ter de 8 à 20 caracteres!');
                                                                $('#txt_telefone').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_telefone').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Telefone2:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_telefone2" name="telefone2" placeholder="Telefone2" onkeyup="revisaCampos();" onchange="
                                                            if(this.value.length<8 || this.value.length>20){
                                                                toastr.error('O Telefone deve ter de 8 à 20 caracteres!');
                                                                $('#txt_telefone2').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_telefone2').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">*Nome Responsável:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_name_responsavel" name="name_responsavel" placeholder="Nome Responsavel" onkeyup="revisaCampos();" onchange="
                                                            if(this.value.length<6 || this.value.length>100){
                                                                toastr.error('O Nome do Responsável deve ter de 6 à 100 caracteres!');
                                                                $('#txt_name_responsavel').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_name_responsavel').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">*Cargo Responsável:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_cargo" name="cargo" placeholder="Cargo Responsavel" onkeyup="revisaCampos();" onchange="
                                                            if(this.value.length<4 || this.value.length>45){
                                                                toastr.error('O Cargo do Responsável deve ter de 6 à 100 caracteres!');
                                                                $('#txt_cargo').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_cargo_').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">*Email:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_email" name="email" placeholder="email" onkeyup="revisaCampos();" onchange="
                                                            if(this.value.length<6 || this.value.length>100){
                                                                toastr.error('O Email deve ter de 6 à 100 caracteres!');
                                                                $('#txt_email').css('border-color','red');
                                                            }
                                                            else if(this.value.search('@') == -1){
                                                                toastr.error('Digite um Email válido');
                                                                $('#txt_email').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_email').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">CEP:</label>
                                                    <div class="col-sm-2">
                                                        <input type="text" class="form-control" id="txt_cep" name="cep" placeholder="cep" onkeyup="revisaCampos();" onchange="
                                                            var cep = document.getElementById('txt_cep').value;
                                                            cep = cep.replace(/\D+/g, '');
                                                            document.getElementById('txt_cep').value = cep;
                                                            if(this.value.length != 8 && this.value){
                                                                toastr.error('O CEP deve ter 8 números!');
                                                                $('#txt_cep').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_cep').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Estado:</label>
                                                    <div class="col-sm-2">
                                                        
                                                        <select  id='opt_estado_name' name="estado" class="normal form-control select2" onchange="revisaCampos();">
                                                            <option value="">Selecione o Estado</option>
                                                            <option value="AC">Acre</option>
                                                            <option value="AL">Alagoas</option>
                                                            <option value="AP">Amapá</option>
                                                            <option value="AM">Amazonas</option>
                                                            <option value="BA">Bahia</option>
                                                            <option value="CE">Ceará</option>
                                                            <option value="ES">Espírito Santo</option>
                                                            <option value="DF">Distrito Federal</option>
                                                            <option value="GO">Goiás</option>
                                                            <option value="MA">Maranhão</option>
                                                            <option value="MT">Mato Grosso</option>
                                                            <option value="MS">Mato Grosso do Sul</option>
                                                            <option value="MG">Minas Gerais</option>
                                                            <option value="PR">Paraná</option>
                                                            <option value="PB">Paraíba</option>
                                                            <option value="PA">Pará</option>
                                                            <option value="PE">Pernambuco</option>
                                                            <option value="PI">Piauí</option>
                                                            <option value="RN">Rio Grande do Norte</option>
                                                            <option value="RS">Rio Grande do Sul</option>
                                                            <option value="RJ">Rio de Janeiro</option>
                                                            <option value="RO">Rondônia</option>
                                                            <option value="RR">Roraima</option>
                                                            <option value="SC">Santa Catarina</option>
                                                            <option value="SE">Sergipe</option>
                                                            <option value="SP">São Paulo</option>
                                                            <option value="TO">Tocantins</option>
                                                        </select>
                                                    </div>
                                                    <label class="col-sm-1 control-label">Cidade:</label>
                                                    <div class="col-sm-3">
                                                     
                                                        <input type="text" class="form-control" id="txt_cidade" name="cidade" placeholder="cidade" onkeyup="revisaCampos();">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Bairro:</label>
                                                    <div class="col-sm-3">
                                                        <input type="text" class="form-control" id="txt_bairro" name="bairro" placeholder="bairro" onkeyup="revisaCampos();" onchange="
                                                            if((this.value.length < 6 || this.value.length > 100) && this.value){
                                                                toastr.error('O Bairro deve ter de 6 à 100 caracteres!');
                                                                $('#txt_bairro').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_bairro').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Rua:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_rua" name="rua" placeholder="rua" onkeyup="revisaCampos();" onchange="
                                                            if((this.value.length < 6 || this.value.length > 100) && this.value){
                                                                toastr.error('A Rua deve ter de 6 à 100 caracteres!');
                                                                $('#txt_rua').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_rua').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>
                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Numero:</label>
                                                    <div class="col-sm-1">
                                                        <input type="text" class="form-control" style="padding-right:1px;" id="txt_numero" name="numero" placeholder="Nº" onkeyup="revisaCampos();" onchange="
                                                            var numero = document.getElementById('txt_numero').value;
                                                            numero = numero.replace(/\D+/g, '');
                                                            document.getElementById('txt_numero').value = numero;
                                                            if((this.value.length < 1 || this.value.length > 5) && this.value){
                                                                toastr.error('O Número deve ter de 1 à 5 números!');
                                                                $('#txt_numero').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_numero').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                    <label class="col-sm-2 control-label">Complemento:</label>
                                                    <div class="col-sm-3">
                                                        <input type="text" maxlength="30" class="form-control" id="txt_complemento" name="complemento" placeholder="complemento" onkeyup="revisaCampos();" onchange="
                                                            if(this.value.length >){
                                                                toastr.error('O Complamento deve ter menos de 30 caracteres!');
                                                                $('#txt_complemento').css('border-color','red');
                                                            }
                                                            else{
                                                                $('#txt_complemento').css('border-color','#d2d6de');
                                                            }
                                                            revisaCampos();
                                                        ">
                                                    </div>
                                                </div>

                                                <div id="div_observation" class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Observação:</label>
                                                    <div class="col-sm-6">
                                                        <textarea type="text" class="form-control" id="txt_observation" name="observation"></textarea>
                                                    </div>
                                                </div>

                                                <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Serviços:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_service_uuid' name="service_uuid" class="normal form-control select2" onchange="revisaCampos();">
                                                            <option value="">Selecione um tipo de serviço</option>
                                                            <?php
                                                                foreach($services as $value){
                                                                    echo("<option value='".$value["uuid"]."'>".$value["name"]."</option>");
                                                                }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div>
                                                <!-- <div class="form-group has-feedback">
                                                    <label class="col-sm-2 control-label">Compania:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_company_uuid' name="company_uuid" class="normal form-control select2" onchange="revisaCampos();">
                                                            <option value="">Selecione uma compania</option>
                                                            <?php
                                                                // foreach($companies as $value){
                                                                //     echo("<option value='".$value["uuid"]."'>".$value["name"]."</option>");
                                                                // }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div> -->
                                                <!-- restrito para admin e super -->
                                                <div id="div_admin">
                                                    <div class="form-group has-feedback">
                                                        <label class="col-sm-2 control-label">Status:</label>
                                                        <div class="col-sm-6">
                                                            <select  id='opt_status' disabled="true" name="status" class="normal form-control select2" onchange="revisaCampos();">
                                                                <option value="" >Selecione o status</option>
                                                                <option value="7" selected>Sem Consultor</option>
                                                                <option value="1" >Pendente</option>
                                                                <option value="2" >Cliente contatado</option>
                                                                <option value="3" >Visita Realizada</option>
                                                                <option value="4" >Proposta Enviada</option>
                                                                <option value="5" >Negocio ganho</option>
                                                                <option value="6" >Negocio perdido</option>
                                                            </select>
                                                            <input type="hidden" id="txt_status" name="status" value="7">
                                                        </div>
                                                        <div class="col-sm-3">
                                                            <button type="button" class="btn btn-default btn-xs" title="Ver observações" onclick="ver_observacao();"><i class="fa fa-list"></i></button>
                                                            <button type="button" class="btn btn-default btn-xs" title="Adicionar observação" id="btn_show_observacao" onclick="
                                                                $('#div_observation_status').show();
                                                                $('#btn_hide_observacao').show();
                                                                $('#btn_show_observacao').hide();"><i class="fa fa-plus"></i>
                                                            </button>
                                                            <button type="button" class="btn btn-default btn-xs" title="Adicionar observação" id="btn_hide_observacao" onclick="
                                                                $('#div_observation_status').hide();
                                                                $('#btn_show_observacao').show();
                                                                $('#btn_hide_observacao').hide();
                                                                $('#txa_observation').val('')" style="display:none;"><i class="fa fa-minus"></i>
                                                            </button>
                                                        </div>
                                                    </div>

                                                    <div id="div_observation_status" class="form-group has-feedback" style="display:none;">
                                                        <label class="col-sm-2 control-label">Observação Status:</label>
                                                        <div class="col-sm-6">
                                                            <textarea class="form-control" id="txa_observation" name="observation_status"></textarea>
                                                        </div>
                                                    </div>

                                                    <div class="form-group has-feedback">
                                                        <label class="col-sm-2 control-label">Consultor:</label>
                                                        <div class="col-sm-6">
                                                            <select  id='opt_user_uuid' name="user_uuid" class="normal form-control select2" onchange="revisaCampos();">
                                                                <option value="">Selecione o consultor responsável</option>
                                                                <?php
                                                                    foreach($consultores as $value){
                                                                        echo("<option value='".$value["uuid"]."'>".$value["name"]."</option>");
                                                                    }
                                                                ?>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <div class="form-group has-feedback">
                                                        <label class="col-sm-2 control-label">Bônus:</label>
                                                        <div class="col-sm-3">
                                                            <button type="button" class="btn btn-default btn-xs" onclick="ver_comisao();"><i class="fa fa-eye"></i></button>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-sm-3 col-sm-offset-2">
                                                        <button id="editar" type="submit" class="btn btn-primary" onclick="" disabled="true">Editar</button>
                                                    </div>
                                                </div>
                                            </div>    
                                        </form>
                                    </div>

                                    <!-- MODAL VER COMISSÕES-->
                                    <div class="modal fade" id="modal_commission" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                        <div class="modal-dialog modal-lg" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title" id="myModalLabel">Bônus</h4>
                                                </div>
                                                <div class="modal-body">
                                                <table id='table_commissions' class="table table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th>Valor</th>
                                                            <th>Data</th>
                                                            <th>Status</th>
                                                            <th>Observação</th>
                                                            <th width="10"><i class="fa fa-edit"></i></th>
                                                            <th width="10"><i class="fa fa-trash-o"></i></th>
                                                        </tr>
                                                    </thead>
                                                    <tbody id="tbody_commission">
                                                    
                                                    </tbody>
                                                </table>

                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- MODAL OBSERVACAO-->
                                    <div class="modal fade" id="modal_observation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                        <div class="modal-dialog modal-lg" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title" id="myModalLabel">Observações</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <input type="hidden" id="txt_status_modal">
                                                    <!-- <button class="btn btn-default pull-right" onclick="modal_adicionar_observacao()"><i class="fa fa-plus"></i> Adicionar Observação</button> -->
                                                    <table id='table_observation' class="table table-hover">
                                                        <thead>
                                                            <tr>
                                                                <th>Status</th>
                                                                <th width="550">Observação</th>
                                                                <th width="150">Data/hora da criação</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody id="tbody_observation">
                                                        
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- MODAL ADICIONAR OBSERVACAO-->
                                    <div class="modal fade" id="modal_add_observation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                        <div class="modal-dialog modal-lg" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title" id="myModalLabel">Adicionar Observação</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <button class="btn btn-default pull-right" onclick="add_observacao()"><i class="fa fa-plus"></i></button>
                                                    <div id="div_observation" class="form-group has-feedback">
                                                        <div class="col-sm-11">
                                                            <input type="text" class="form-control" id="txt_observation_modal" name="observation_modal">
                                                        </div>
                                                    </div>
                                                    <br>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    
                                </div><!--box-body-->
                            </div>
                        </div>    
                    </div><!--row-->    
                </section> <!--content-->   
            </div><!--corpoGeral-->  
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div><!-- wrapper -->


        <script src="/template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="/template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="/template/dist/js/app.min.js" type="text/javascript"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script> 
	<!-- InputMask -->
	    <script src="/template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="/template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="/template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="/template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="/template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		<!-- daterangepicker -->
		<script src="/template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="/template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
		<script src="/template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="/template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="/template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="/template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="/template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="/template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="/template/bower_components/select2/dist/js/select2.min.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="/template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <!-- jQuery 3 -->
        <!-- <script src="template/bower_components/jquery/dist/jquery.min.js"></script> -->
        <!-- Bootstrap 3.3.7 -->
        <!-- <script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script> -->
        <!-- iCheck -->
        <!-- <script src="template/plugins/iCheck/icheck.min.js"></script> -->

        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->

        <script>
        $('.select2').select2();
        $('#txt_telefone,#txt_telefone2').mask("(99) 9999-9999?9");
       
            function tratarValor(valor){
                valor = valor.replace('.', ',');
                var p = valor.indexOf(",");
                if((valor.length-p) == 3 && p != -1){
                    valor = valor.replace(',', '');
                }
                else{
                    valor = valor * 100;
                }
                $("#txt_value_commission").val(valor);

            }

            function carregaIndicacao(){
                var uuid = $('#opt_indication_uuid').val();
                $.ajax({
                    type: 'POST',
                    url: '/carregaEditarIndicacao',
                    data: 'uuid='+uuid,
                    dataType: 'json',
                    success: function (dados) {
                        $('#txt_name').val(dados['name']);
                        $('#txt_cpf_cnpj').val(dados['cpf_cnpj']);
                        $('#txt_telefone').val(dados['telefone']);
                        $('#txt_telefone2').val(dados['telefone2']);
                        $('#txt_name_responsavel').val(dados['name_responsavel']);
                        $('#txt_cargo').val(dados['cargo']);
                        $('#txt_email').val(dados['email']);
                        $('#txt_cep').val(dados['cep']);
                        $('#opt_estado_name').val(dados['estado']);
                        $('#opt_estado_name').trigger('change');
                        $('#txt_cidade').val(dados['cidade']);
                        $('#txt_bairro').val(dados['bairro']);
                        $('#txt_rua').val(dados['rua']);
                        $('#txt_numero').val(dados['numero']);
                        $('#txt_complemento').val(dados['complemento']);
                        $('#txt_observation').val(dados['observation']);
                        $('#txt_value_commission').val(dados['value_commission']);
                        $('#txt_status_modal').val(dados['status']);
                        var value = dados['value_commission'];
                        if(value.length < 3 && value.length == 2){
                            value = '0'+value;
                        }
                        else if(value.length < 3 && value.length == 1){
                            value = '00' + value;
                        }
                        var final = value.substring(value.length - 2, value.length);
                        value = value.substring(0,value.length - 2);
                        $('#txt_value_commission2').val(value+','+final);


                        $('#opt_service_uuid').val(dados['service_uuid']);
                        $('#opt_service_uuid').trigger('change');
                        $('#opt_commission').val(dados['commission']);
                        $('#opt_commission').trigger('change');
                        $('#opt_user_uuid').val(dados['user_uuid']);
                        $('#opt_user_uuid').trigger('change');
                        $('#opt_status').val(dados['status']);
                        $('#opt_status').trigger('change');
// alert(dados['start_date'].slice(0,4));
// alert(dados['start_date'].slice(5,7));
//                         var start_m = dados['start_date'].slice(5,7);
//                         if(parseInt(start_m) < 10){

//                         }
                        if(dados['start_date'] != null){
                            $('#opt_start_data_y').val(dados['start_date'].slice(0,4));
                            $('#opt_start_data_y').trigger('change');
                            $('#opt_start_data_m').val(parseInt(dados['start_date'].slice(5,7)));
                            $('#opt_start_data_m').trigger('change');
                            $('#opt_end_data_y').val(dados['end_date'].slice(0,4));
                            $('#opt_end_data_y').trigger('change');
                            $('#opt_end_data_m').val(parseInt(dados['end_date'].slice(5,7)));
                            $('#opt_end_data_m').trigger('change');
                        }

                    //     $('#opt_user_type').val(dados['user_type']);
                    //     $('#opt_user_type').trigger('change');
                    //     $('#txt_email').val(dados['email']);
                    //     $('#txt_password').val(dados['password']);
                    //     $('#txt_confirm_password').val(dados['password']);
                    //     $('#txt_cpf').val(dados['cpf']);
                    //     //$('#opt_company_uuid').val(dados['company_uuid']);
                    //    // $('#opt_company_uuid').trigger('change');
                    //     $('#opt_status').val(dados['status']);
                    //     $('#opt_status').trigger('change');
                        revisaCampos();

                        // 'name'=>$metadata['name'],
                        //                     'cpf_cnpj'=>$metadata['cpf_cnpj'], 
                        //                     'telefone'=>$metadata['telefone'],
                        //                     'name_responsavel'=>$metadata['name_responsavel'],
                        //                     'email'=>$metadata['email'],
                        //                     'cep'=>$metadata['cep'],
                        //                     'estado'=>$metadata['estado'],
                        //                     'cidade'=>$metadata['cidade'],
                        //                     'bairro'=>$metadata['bairro'],
                        //                     'rua'=>$metadata['rua'],
                        //                     'numero'=>$metadata['numero'],
                        //                     'complemento'=>$metadata['complemento'],
                        //                     'service_uuid'=>$metadata['service_uuid'],
                        //                     //'company_uuid'=>$metadata['company_uuid'],
                        //                     'status'=>$metadata['status'],
                        //                     'commission'=>$metadata['commission'],
                        //                     'user_uuid'=>$metadata['user_uuid']]);
                        //var status = ["","Pendente","Cliente contatado","Visita Realizada","Proposta Enviada","Negocio ganho","Negocio perdido"];
                        var tabela = "";
                        var status = "";
                        
                        for(var i = 0; i<dados['observation_status'].length; i++) {
                            tabela += '<tr>';
                            switch (dados['observation_status'][i]['status']) {
                                case "1":
                                    status = 'Pendente';
                                    break;
                                case "2":
                                    status = 'Cliente contatado';
                                    break;
                                case "3":
                                    status = 'Visita Realizada';
                                    break;
                                case "4":
                                    status = 'Proposta Enviada';
                                    break;
                                case "5":
                                    status = 'Negocio ganho';
                                    break;
                                case "6":
                                    status = 'Negocio perdido';
                                    break;
                                case "7":
                                    status = 'Sem Consultor';
                                    break;
                                default:
                                    break;
                            }
                            var data = dados['observation_status'][i]['create_time'];
                            
                            var vetor = data.split(" ");
                            var vetor2 = vetor[0].split("-");
                            
                            var ano = vetor2[0];
                            var mes = vetor2[1];
                            var dia = vetor2[2];
                            var horario = vetor[1];

                            tabela += "<td>"+status+"</td>";
                            tabela += '<td>'+dados['observation_status'][i]['observation']+'</td>';
                            tabela += "<td>"+dia+"/"+mes+"/"+ano+" - "+horario+"</td>";

                            // for(var t = 0; t <dados['observation_status'].length; t++){
                            //     if(dados['observation_status'][t]['status'] == i){
                            //         teste = true
                            //     }
                            // }
                            // if(!teste){
                            //     tabela += "<td></td>";
                            // }
                            tabela += '</tr>';
                        }
                        $('#tbody_observation').html(tabela);
                        $('#txt_telefone,#txt_telefone2').mask("(99) 9999-9999?9");
                    },
                    error: function (dados){
                        toastr.error('Erro ao carregar Indicação');
                    }
                });
            }

            function revisaCampos(){
                if($('#opt_user_uuid').val() == ''){
                    $("#opt_status option[value='7']").removeAttr("disabled","false");
                    $('#opt_status').val('7');
                    $("#opt_status").attr("disabled","true"); 
                    $("#txt_status").removeAttr("disabled");     
                    $('#opt_status').select2();
                }   
                else{
                    $("#opt_status").removeAttr("disabled");   
                    $("#txt_status").attr("disabled","true");
                    if($('#opt_status').val() == "7"){
                        $('#opt_status').val('1');
                    }
                    $("#opt_status option[value='7']").attr("disabled","true");
                    $('#opt_status').select2();
                }

                if($("#opt_commission").val() == '2'){
                    $("#div_data").show();
                }
                else{
                    $("#div_data").hide();
                }

                if($('#txt_name').val() == '' || document.getElementById("txt_name").style.borderColor == 'red' ||
                document.getElementById("txt_cpf_cnpj").style.borderColor == 'red' ||
                $('#txt_telefone').val() == '' || document.getElementById("txt_telefone").style.borderColor == 'red' ||
                $('#txt_name_responsavel').val() == '' || document.getElementById("txt_name_responsavel").style.borderColor == 'red' ||
                $('#txt_cargo').val() == '' || document.getElementById("txt_cargo").style.borderColor == 'red' ||
                $('#txt_email').val() == '' || document.getElementById("txt_email").style.borderColor == 'red' ||
                document.getElementById("txt_cep").style.borderColor == 'red' ||
                document.getElementById("txt_telefone2").style.borderColor == 'red' ||
                document.getElementById("txt_cidade").style.borderColor == 'red' ||
                document.getElementById("txt_bairro").style.borderColor == 'red' ||
                document.getElementById("txt_rua").style.borderColor == 'red' ||
                document.getElementById("txt_numero").style.borderColor == 'red' ||
                $('#opt_service_uuid').val() == '' ||
                //$('#opt_company_uuid').val() == '' ||
                $('#opt_status').val() == '' ||
                $('#txt_value_commission').val() == ''){
                    $("#editar").attr("disabled","true");    
                }
                else{
                    $("#editar").removeAttr("disabled","false");    
                }
            }

            $("#txt_cep").focusout(function(){//API viacep
                $.ajax({
                    type: 'POST',
                    url: '/apiViaCEP',
                    dataType: 'json',
                    data: 'id='+$("#txt_cep").val(),
                    success: function(resposta){
                        $("#txt_rua").val(resposta.logradouro);
                        $("#txt_complemento").val(resposta.complemento);
                        $("#txt_bairro").val(resposta.bairro);
                        $("#txt_cidade").val(resposta.localidade);
                        $("#opt_estado_name").val(resposta.uf);
                        $('#opt_estado_name').trigger('change');
                    }
                });
            });

            function ver_observacao(){
                $('#modal_observation').modal();
            }

            function modal_adicionar_observacao(){
                $('#txt_observation_modal').val("");
                $('#modal_add_observation').modal();
            }

            function add_observacao(){
                var observacao = $('#txt_observation_modal').val();
                if(observacao == "" || observacao == " " || !observacao){
                    toastr.warning('Digite uma observação');
                    return false;
                }
                var status = $('#txt_status_modal').val();
                var uuid = $('#opt_indication_uuid').val();

                $.ajax({
                    type: 'POST',
                    url: '/addObservacao',
                    data: 'uuid='+uuid+'&status='+status+'&observation='+observacao,
                    dataType: 'json',
                    success: function (dados) {
                        if(dados){
                            toastr.success('Adicionado');
                            $('#modal_add_observation').modal('hide');
                            var coluna = "<tr>";
                            switch (status) {
                                case "1":
                                    status = 'Pendente';
                                    break;
                                case "2":
                                    status = 'Cliente contatado';
                                    break;
                                case "3":
                                    status = 'Visita Realizada';
                                    break;
                                case "4":
                                    status = 'Proposta Enviada';
                                    break;
                                case "5":
                                    status = 'Negocio ganho';
                                    break;
                                case "6":
                                    status = 'Negocio perdido';
                                    break;
                                case "7":
                                    status = 'Sem Consultor';
                                    break;
                                default:
                                    break;
                            }
                            coluna += "<td>"+dados.status+"</td>";
                            coluna += "<td>"+dados.observacao+"</td>";
                            coluna += "<td>"+dados.data+"</td></tr>";
                            $('#table_observation').append(coluna);
                        }
                        else{
                            toastr.error('Erro ao adicionar');
                        }
                    }
                });
            }

            function ver_comisao(){
                uuid = $('#opt_indication_uuid').val();
                $('#tbody_commission').html('');
                var t = $('#table_commissions').dataTable();t.fnDestroy();
                $.get('/getCommissionsIndication/'+uuid,function(data){
                    var resposta = JSON.parse(data);
                    var data = new Date();
                    var mes_atual = data.getMonth()+1;
                    var ano_atual = data.getFullYear();

                    var tabela = "";
                    var status = "";
                    var dia = '';
                    var mes = '';
                    var ano = '';
                    var data = '';
                    var observation = '';
                    var botao = '';
                    for(var i=0; i<resposta.length;i++){

                        ano  = resposta[i]['date'].split("-")[0];
                        mes  = resposta[i]['date'].split("-")[1];
                        dia  = resposta[i]['date'].split("-")[2];

                        

                        if(mes_atual == mes && ano_atual == ano)    data = "-> "+dia + '/' + (mes) + '/' + (ano);
                        else                                        data = dia + '/' + (mes) + '/' + (ano);

                        if(resposta[i]['observation'] == null)  observation = "<td></td>";
                        else                                    observation = "<td>"+resposta[i]['observation']+"</td>";
                        
                        botao = '';
                        <?php if($user_type == 1 || $user_type == 2){?>
                            if(resposta[i]['paid'] == 1)    botao = "<button onclick='payCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>";
                            else                            botao = "<button onclick='unpaidCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>";
                        <?php }?>

                        if(resposta[i]['paid'] == 1)    status = "<td style='color:red' id=pay"+i+">Não Pago "+botao+"</td>";
                        else                            status = "<td style='color:green' id=pay"+i+">Pago "+botao+"</td>";
                            
                        tabela += '<tr id="'+i+'">';
                        tabela += '<td>R$'+(resposta[i]['value_commission']/100)+'</td>';
                        tabela += '<td>'+data+'</td>';
                        tabela += status;
                        tabela += observation;
                        <?php if($user_type == 1 || $user_type == 2){?>
                            tabela += '<td><button onclick="editarComissao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                            tabela += '<td><button onclick="excluirComissao(\''+resposta[i]['uuid']+'\',\''+resposta[i]['uuid']+'4\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-trash-o"></i></button></td>';
                        <?php }else{?>
                            tabela += '<td></td>'
                            tabela += '<td></td>'
                        <?php }?>
                        tabela += '</tr>';

                    }
                    $('#tbody_commission').html(tabela);

                    $('#table_commissions').DataTable({
                        'autoWidth'   : true,
                        'aLengthMenu' :	[[10, 25, 50, -1], [10, 25, 50, "Tudo"]],
                        'oLanguage'   : {"sEmptyTable": "Nenhum registro encontrado", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando 0 até 0 de 0 registros", "sInfoFiltered": "(Filtrados de _MAX_ registros)", "sInfoPostFix": "", "sInfoThousands": ".", "sLengthMenu": "_MENU_ resultados por página", "sLoadingRecords": "Carregando...", "sProcessing": "Processando...", "sZeroRecords": "Nenhum registro encontrado", "sSearch": "Pesquisar", "oPaginate": { "sNext": "Próximo", "sPrevious": "Anterior", "sFirst": "Primeiro", "sLast": "Último" }, "oAria": { "sSortAscending": ": Ordenar colunas de forma ascendente", "sSortDescending": ": Ordenar colunas de forma descendente"}}
                    });
                });
                
                $('#modal_commission').modal();
            }

            function editarComissao(uuid){
                $("#myForm").attr("action","/editaComissao/"+uuid);    
                $("#myForm").submit();
            }

            function excluirComissao(uuid,num){
                if(confirm("Deseja deletar a indicação?")){
                    $.ajax({
                    type: 'POST',
                    url: '/excluiComissao',
                    dataType: 'json',
                    data: 'uuid='+uuid,
                    success: function(resposta){

                        
                        if(resposta){
                            $("#"+num+"").remove();
                            toastr.success('Deletado');
                        }
                    }
                    
                    });
                }
            }

            function payCommission(uuid,i){
                var r = confirm("Deseja pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Pago <button onclick='unpaidCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>");
                            $('#pay'+i).css("color","green");
                        }
                        else{
                            toastr.error('Falha ao Pagar');    
                        }
                    });
                }
            }

            function unpaidCommission(uuid,i){
                var r = confirm("Deseja não pagar a comissão?");
                if(r == true){
                    $.get('unpaidCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Não Pago <button onclick='payCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>");
                            $('#pay'+i).css("color","red");
                        }
                    });
                }
            }

            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }

                var uuid = '<?php echo($uuid); ?>';
                if(uuid != ''){
                    $('#opt_indication_uuid').val(uuid);
                    $('#opt_indication_uuid').trigger('change');
                }

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                 ?>
			});
        </script>	
    </body>
</html>