<?php
    
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
    //$users  = isset($users) ? $users : '';//uuids dos usuarios
    $validate = isset($message['validate']) ? $message['validate'] : '';//mensagem do validador dos campos
    $user_type = $_SESSION['user']['user_type'];//tipo de usuario
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Lista Indicação</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="template/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link rel="stylesheet" href="template/bower_components/select2/dist/css/select2.min.css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script>
		   // $('.select2').select2();
	    </script>
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        <div class="wrapper">

            <?php include_once(__DIR__.'/../header.phtml'); ?>
            
            <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Login
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Listar Indicação</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                            

                                        <form id="myForm" class="form-horizontal" action="" method="get">
                                            <div class="box-body">
                                                <div class="form-group" id="div_user">
                                                    <label class="col-sm-2 control-label">Indicação:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_indication' name="indication" class="normal form-control select2" onchange="editarIndicacao($('#opt_user').val());">
                                                            <option value="">Selecione a Indicação</option>
                                                        </select> 
                                                    </div>    
                                                </div>
                                                <div class="form-group" id="div_busca">
                                                    <label class="col-sm-2 control-label">Tipo de busca:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_busca' name="busca" class="normal form-control select2" onchange="
                                                            if($('#opt_busca').val() == 1){
                                                                $('#div_cpf_cnpj').show();
                                                                $('#div_email').hide();
                                                                $('#div_telefone').hide();
                                                                $('#div_nome_responsavel').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 2){
                                                                $('#div_telefone').show();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_email').hide();
                                                                $('#div_nome_responsavel').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 3){
                                                                $('#div_email').show();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_telefone').hide();
                                                                $('#div_nome_responsavel').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 4){
                                                                $('#div_email').hide();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_telefone').hide();
                                                                $('#div_nome_responsavel').show();
                                                            }
                                                            else{
                                                                $('#div_email').hide();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_nome_responsavel').hide();
                                                                $('#div_telefone').hide();
                                                            }
                                                        ">
                                                            <option value="">Selecione o tipo de busca</option>
                                                            <option value="1">CPF/CNPJ</option>
                                                            <option value="2">Telefone</option>
                                                            <option value="3">Email</option>
                                                            <option value="4">Nome Responsável</option>
                                                        </select>
                                                    </div>    
                                                </div>
                                                <div class="form-group" id="div_email" style="display:none">
                                                    <label class="col-sm-2 control-label">Email:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_email" name="email" placeholder="Email" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_cpf_cnpj" style="display:none">
                                                    <label class="col-sm-2 control-label">CPF/CNPJ:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_cpf_cnpj" name="cpf_cnpj" placeholder="CPF" onkeyup="
                                                            var cpf = document.getElementById('txt_cpf_cnpj').value;
                                                            cpf = cpf.replace(/\D+/g, '');
                                                            document.getElementById('txt_cpf_cnpj').value = cpf;
                                                            //atualizaUsuario('cpf',$('#txt_cpf').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_telefone" style="display:none">
                                                    <label class="col-sm-2 control-label">Telefone:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_telefone" name="telefone" placeholder="Telefone" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_nome_responsavel" style="display:none">
                                                    <label class="col-sm-2 control-label">Nome Responsável:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_nome_responsavel" name="nome_responsavel" placeholder="Telefone" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_busca">
                                                    <label class="col-sm-2 control-label">Status:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_status' name="status" class="normal form-control select2" onchange="">
                                                            <option value="">Selecione o Status</option>
                                                            <option value="1">Pendente</option>
                                                            <option value="2">Cliente contatado</option>
                                                            <option value="3">Visita Realizada</option>
                                                            <option value="4">Proposta Enviada</option>
                                                            <option value="5">Negócio ganho</option>
                                                            <option value="6">Negócio perdido</option>
                                                        </select>
                                                    </div>    
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-sm-3 col-sm-offset-2">
                                                        <button id="buscar" type="button" class="btn btn-primary" onclick="listaUsuarios()">Buscar</button>
                                                    </div>
                                                </div>
                                            </div>    

                                    </div>
                                </div><!--box-body-->
                            </div>
                        </div>    
                    </div><!--row-->    

                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Lista de Usuários</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-sm-12 col-xs-6">
                                            <div class="description-block">
                                                <div id="div_lista">
                                                    <div class="table-responsive">
                                                        <div id="id_tabela" style="max-height: 500px;overflow-y: auto;">
                                                            <table id="tbUsuario" class="table table-bordered table-striped">
                                                                <thead>
                                                                    <tr>
                                                                        <th width="300">Nome</th>
                                                                        <th>CPF_CNPJ</th>
                                                                        <th>Telefone</th>
                                                                        <th width="300">Nome Responsável</th>
                                                                        <th>Email</th>
                                                                        <th>Status</th> 
                                                                        <th>Comissao</th>  
                                                                        <th width="10"><i class="fa fa-edit"></i></th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody  id="tbIndicacaoBody">

                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>	
                                                </div><!-- Fim his_buscas -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->


                </section> <!--content-->   
            </div><!--corpoGeral-->  
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div><!-- wrapper -->


        <script src="template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		<!-- daterangepicker -->
		<script src="template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
		<script src="template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="template/bower_components/select2/dist/js/select2.min.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <!-- jQuery 3 -->
        <!-- <script src="template/bower_components/jquery/dist/jquery.min.js"></script> -->
        <!-- Bootstrap 3.3.7 -->
        <!-- <script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script> -->
        <!-- iCheck -->
        <!-- <script src="template/plugins/iCheck/icheck.min.js"></script> -->

        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->

        <script>
        $('.select2').select2();

            // function atualizaUsuario(nome,valor){
            //     $.ajax({
            //         type: 'POST',
            //         url: 'filtroUserLista',
            //         dataType: 'json',
            //         data: 'nome='+nome+'&valor='+valor,
            //         success: function(resposta){
            //             $('#opt_user').empty();
            //             $("#opt_user").append(new Option('Selecione um usuário', ''));
            //             for(var i=0; i<resposta.length;i++){
            //                 $("#opt_user").append(new Option(resposta[i]['name'], resposta[i]['uuid']));
            //             }
            //         }
            //     });
            // }

            function listaUsuarios(){
                var tabela = '';
                var status = '';
                var nome = '';
                var valor = '';
                var comissao = '';

                if($('#opt_busca').val() == '' && $('#opt_status').val() == ''){
                    toastr.warning('Digite um valor para a busca');
                    return false;
                }
                
                if($('#opt_status').val() != '')  status = 'status='+$('#opt_status').val();

                if($('#opt_busca').val() == 1 && $('#txt_cpf_cnpj').val() != ''){
                    var nome = 'nome=cpf_cnpj';
                    var valor = '&valor='+$('#txt_cpf_cnpj').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                else if($('#opt_busca').val() == 2 && $('#txt_telefone').val() != ''){
                    var nome = 'nome=telefone';
                    var valor = '&valor='+$('#txt_telefone').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                else if($('#opt_busca').val() == 3 && $('#txt_email').val() != ''){
                    var nome = 'nome=email';
                    var valor = '&valor='+$('#txt_email').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                else if($('#opt_busca').val() == 4 && $('#txt_nome_responsavel').val() != ''){
                    var nome = 'nome=nome_responsavel';
                    var valor = '&valor='+$('#txt_nome_responsavel').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                

                

                $.ajax({
                    type: 'POST',
                    url: 'filtroIndicacaoLista',
                    dataType: 'json',
                    data: nome+valor+status,
                    success: function(resposta){
                        for(var i=0; i<resposta.length;i++){
                            if(resposta[i]['status'] == 1) status = "<td style='color:orange'><b>Pendente</b>";
                            else if(resposta[i]['status'] == 2) status = "<td><b>Cliente contatado</b>";
                            else if(resposta[i]['status'] == 3) status = "<td><b>Visita Realizada</b>";
                            else if(resposta[i]['status'] == 4) status = "<td><b>Proposta Enviada</b>";
                            else if(resposta[i]['status'] == 5) status = "<td style='color:green'><b>Negócio ganho</b>";
                            else if(resposta[i]['status'] == 6) status = "<td style='color:red'><b>Negócio perdido</b>";
                            else status = "<td style='color:red'><b>Cancelado</b>";
                            
                           if(resposta[i]['commission'] == 1)   comissao = "<td>Fixa";
                           else                                 comissao = "<td>Recorrente";
                            
                            tabela += '<tr>';
                            tabela += '<td>'+resposta[i]['name']+'</td>';
                            tabela += '<td>'+resposta[i]['cpf_cnpj']+'</td>';
                            tabela += '<td>'+resposta[i]['telefone']+'</td>';
                            tabela += '<td>'+resposta[i]['name_responsavel']+'</td>';
                            tabela += '<td>'+resposta[i]['email']+'</td>';
                            tabela += status+'</td>';
                            tabela += comissao+'</td>';
                            
                            tabela += '<td><button onclick="editarIndicacao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                            tabela += '</tr>';
                        }
                        $('#tbIndicacaoBody').html(tabela);
                    }
                });
            }

            function editarIndicacao(uuid){
                $("#myForm").attr("action","editaIndicacao/"+uuid);    
                $("#myForm").submit();
            }

            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
                
                $.ajax({
                    type: 'POST',
                    url: 'filtroIndicacaoLista',
                    dataType: 'json',
                    data: 'nome=email&valor=@',
                    success: function(resposta){
                        $('#opt_indication').empty();
                        $("#opt_indication").append(new Option('Selecione uma Indicação', ''));
                        for(var i=0; i<resposta.length;i++){
                            $("#opt_indication").append(new Option(resposta[i]['name'], resposta[i]['uuid']));
                        }
                    }
                });
                

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                 ?>
			});
        </script>	
    </body>
</html>