<?php
    
    $error = isset($message['error']) ? $message['error'] : '';//mensagem de erro
    $success = isset($message['success']) ? $message['success'] : '';//mensagem de sucesso
    //$users  = isset($users) ? $users : '';//uuids dos usuarios
    $validate = isset($message['validate']) ? $message['validate'] : '';//mensagem do validador dos campos
    $user_type = $_SESSION['user']['user_type'];//tipo de usuario
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>INDIQUE | Lista Indicação</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="template/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="template/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="template/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="template/dist/css/AdminLTE.min.css">
        <!-- Data Table -->
        <link rel="stylesheet" href="/template/bower_components/datatables.net-bs/css/dataTables.bootstrap.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="template/plugins/iCheck/square/blue.css">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

        <link href="template/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link rel="stylesheet" href="template/bower_components/select2/dist/css/select2.min.css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <script>
		   // $('.select2').select2();
	    </script>
    </head>

    <body class="skin-blue sidebar-mini" style="height: auto; min-height: 100%;">
        <div class="wrapper">

            <?php include_once(__DIR__.'/../header.phtml'); ?>
            
            <?php include_once(__DIR__.'/../nav_menu.phtml'); ?>

            <div id="corpoGeral" class="content-wrapper" style="min-height: 424px;">

                <section class="content-header">
                    <h1>
                    Indicações
                        <small></small>
                    </h1>
                    <ol class="breadcrumb">
                        <!--<li><a href="#principal" onclick="atualizarPagina('principal.php','#retorno-content', null);"><i class="fa fa-dashboard"></i> Home</a></li>-->
                       
                    </ol>
                </section>

                <section class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Listar Indicação</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                            

                                        <form id="myForm" class="form-horizontal" action="" method="get">
                                            <div class="box-body">
                                                <!-- <div class="form-group" id="div_user">
                                                    <label class="col-sm-2 control-label">Indicação:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_indication' name="indication" class="normal form-control select2" onchange="editarIndicacao($('#opt_user').val());">
                                                            <option value="">Selecione a Indicação</option>
                                                        </select> 
                                                    </div>    
                                                </div> -->
                                                <div class="form-group" id="div_busca" <?php if($user_type == 4) echo("style='display:none;'")?>>
                                                    <label class="col-sm-2 control-label">Tipo de busca:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_busca' name="busca" class="normal form-control select2" onchange=" 
                                                            if($('#opt_busca').val() == 1){
                                                                $('#div_cpf_cnpj').show();
                                                                $('#div_email').hide();
                                                                $('#div_telefone').hide();
                                                                $('#div_nome_responsavel').hide();
                                                                $('#div_nome').hide();
                                                                $('#div_criador').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 2){
                                                                $('#div_telefone').show();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_email').hide();
                                                                $('#div_nome_responsavel').hide();
                                                                $('#div_nome').hide();
                                                                $('#div_criador').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 3){
                                                                $('#div_email').show();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_telefone').hide();
                                                                $('#div_nome_responsavel').hide();
                                                                $('#div_nome').hide();
                                                                $('#div_criador').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 4){
                                                                $('#div_email').hide();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_telefone').hide();
                                                                $('#div_nome_responsavel').show();
                                                                $('#div_nome').hide();
                                                                $('#div_criador').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 5){
                                                                $('#div_email').hide();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_telefone').hide();
                                                                $('#div_nome_responsavel').hide();
                                                                $('#div_nome').show();
                                                                $('#div_criador').hide();
                                                            }
                                                            else if($('#opt_busca').val() == 6){
                                                                $('#div_criador').show();
                                                                $('#div_email').hide();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_telefone').hide();
                                                                $('#div_nome_responsavel').hide();
                                                                $('#div_nome').hide();
                                                                carregaIndicadores();
                                                            }
                                                            else{
                                                                $('#div_email').hide();
                                                                $('#div_cpf_cnpj').hide();
                                                                $('#div_nome_responsavel').hide();
                                                                $('#div_telefone').hide();
                                                                $('#div_nome').hide();
                                                                $('#div_criador').hide();
                                                            }
                                                        ">
                                                            <option value="">Selecione o tipo de busca</option>
                                                            <option value="1">CPF/CNPJ</option>
                                                            <option value="2">Telefone</option>
                                                            <option value="3">Email</option>
                                                            <option value="4">Nome Responsável</option>
                                                            <option value="5">Nome Indicação</option>
                                                            <option value="6">Criador da Indicação</option>
                                                        </select>
                                                    </div>    
                                                </div>
                                                <div class="form-group" id="div_email" style="display:none">
                                                    <label class="col-sm-2 control-label">Email:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_email" name="email" placeholder="Email" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_cpf_cnpj" style="display:none">
                                                    <label class="col-sm-2 control-label">CPF/CNPJ:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_cpf_cnpj" name="cpf_cnpj" placeholder="CPF" onkeyup="
                                                            var cpf = document.getElementById('txt_cpf_cnpj').value;
                                                            cpf = cpf.replace(/\D+/g, '');
                                                            document.getElementById('txt_cpf_cnpj').value = cpf;
                                                            //atualizaUsuario('cpf',$('#txt_cpf').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_telefone" style="display:none">
                                                    <label class="col-sm-2 control-label">Telefone:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_telefone" name="telefone" placeholder="Telefone" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_nome_responsavel" style="display:none">
                                                    <label class="col-sm-2 control-label">Nome Responsável:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_nome_responsavel" name="nome_responsavel" placeholder="Nome Responsável" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_nome" style="display:none">
                                                    <label class="col-sm-2 control-label">Nome:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_nome" name="nome" placeholder="Nome" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                </div>
                                                <div class="form-group" id="div_criador" style="display:none;">
                                                    <label class="col-sm-2 control-label">Indicador:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" class="form-control" id="txt_indicador" name="indicador" placeholder="Nome" onkeyup="//atualizaUsuario('email',$('#txt_email').val());">
                                                    </div>
                                                    <!-- <div class="col-sm-6">
                                                        <select  id='opt_creator' name="creator" class="normal form-control select2" onchange="">
                                                            <option value="">Selecione o Indicador</option>
                                                            
                                                        </select>
                                                    </div> -->
                                                </div>
                                                <div class="form-group" id="div_busca">
                                                    <label class="col-sm-2 control-label">Status:</label>
                                                    <div class="col-sm-6">
                                                        <select  id='opt_status' name="status" class="normal form-control select2" onchange="">
                                                            <option value="0" selected>Selecione o Status</option>
                                                            <option value="7">Sem Consultor</option>
                                                            <option value="1">Pendente</option>
                                                            <option value="2">Cliente Contatado</option>
                                                            <option value="3">Visita Realizada</option>
                                                            <option value="4">Proposta Enviada</option>
                                                            <option value="5">Negócio Ganho</option>
                                                            <option value="6">Negócio Perdido</option>
                                                        </select>
                                                    </div>    
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-sm-3 col-sm-offset-2">
                                                        <button id="buscar" type="button" class="btn btn-primary" onclick="listaIndicacoes()">Buscar</button>
                                                    </div>
                                                </div>
                                            </div>    

                                    </div>
                                </div><!--box-body-->
                            </div>
                        </div>    
                    </div><!--row-->    

                    <div class="row">
                        <div class="col-md-12">
                            <!-- TABLE: LATEST ORDERS -->
                            <div class="box box-info">
                                <div class="box-header with-border">
                                <h3 class="box-title">Lista de Usuários</h3>
                                <div class="box-tools pull-right">
                                    
                                </div>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-sm-12 col-xs-6">
                                            
                                                <div id="div_lista">
                                                    <div class="table-responsive">
                                                        <div id="id_tabela" style="max-height: 500px;overflow-y: auto;">
                                                            <table id="tbIndicacao" class="table table-bordered table-striped">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Comissões</th>
                                                                        <th width="300">Nome</th>
                                                                        <th>CPF_CNPJ</th>
                                                                        <th>Telefone</th>
                                                                        <th width="300">Nome Responsável</th>
                                                                        <th>Email</th>
                                                                        <th>Status</th> 
                                                                        <th>Comissao</th>  
                                                                        <th>Consultor</th>
                                                                       
                                                                        <?php if($user_type != 4){?>
                                                                            <th width="10"><i class="fa fa-edit"></i></th>
                                                                            <th width="10"><i class="fa fa-trash-o"></i></th>
                                                                        <?php }?>
                                                                            <th width="10"><i class="fa fa-list"></i></th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody  id="tbIndicacaoBody">

                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>	
                                                </div><!-- Fim his_buscas -->
                                            
                                        </div>
                                    </div>
                                </div>
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->


                    <!-- MODAL VER COMISSÕES-->
                    <div class="modal fade" id="modal_commission" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Bônus</h4>
                                </div>
                                <div class="modal-body">
                                <table id='table_commissions' class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Valor</th>
                                            <th>Data</th>
                                            <th>Status</th>
                                            <th>Observação</th>
                                            <th width="10"><i class="fa fa-edit"></i></th>
                                            <th width="10"><i class="fa fa-trash-o"></i></th>
                                        </tr>
                                    </thead>
                                    <tbody id="tbody_commission">
                                    
                                    </tbody>
                                </table>

                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- MODAL OBSERVACAO-->
                    <div class="modal fade" id="modal_observation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Observações</h4>
                                </div>
                                <div class="modal-body">
                                    <input type="hidden" id="txt_status_modal">
                                    <!-- <button class="btn btn-default pull-right" onclick="modal_adicionar_observacao()"><i class="fa fa-plus"></i> Adicionar Observação</button> -->
                                    <table id='table_observation' class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Status</th>
                                                <th width="550">Observação</th>
                                                <th width="150">Data/hora da criação</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tbody_observation">
                                        
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- MODAL ADICIONAR OBSERVACAO-->
                    <div class="modal fade" id="modal_add_observation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Adicionar Observação</h4>
                                </div>
                                <div class="modal-body">
                                    <button class="btn btn-default pull-right" onclick="add_observacao()"><i class="fa fa-plus"></i></button>
                                    <div id="div_observation" class="form-group has-feedback">
                                        <div class="col-sm-11">
                                            <input type="text" class="form-control" id="txt_observation_modal" name="observation_modal">
                                        </div>
                                    </div>
                                    <br>
                                </div>
                            </div>
                        </div>
                    </div>


                </section> <!--content-->   
            </div><!--corpoGeral-->  
            <?php include_once(__DIR__.'/../footer.phtml'); ?>
        </div><!-- wrapper -->


        <script src="template/bower_components/jquery/dist/jquery.min.js"></script>
		<script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		 <!-- FastClick -->
		<!-- <script src='plugins/fastclick/fastclick.min.js'></script> -->
		<!-- AdminLTE App -->
        <script src="template/dist/js/app.min.js" type="text/javascript"></script>
 
	<!-- InputMask -->
	    <script src="template/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
		<script src="template/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
		<!-- Sparkline -->
		<script src="template/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
		<!-- jvectormap -->
		<script src="template/bower_components/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
		<script src="template/bower_components/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
		<!-- jQuery Knob Chart -->
		<script src="template/bower_components/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>
		<!-- daterangepicker -->
		<script src="template/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
		<!-- datepicker -->
		<script src="template/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
	<!-- DATA TABES SCRIPT -->
		<script src="template/bower_components/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
		 <script src="template/bower_components/datatables.net-bs/js/dataTables.bootstrap.js" type="text/javascript"></script>
		<!-- iCheck -->
		<script src="template/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
		<!-- SlimScroll 1.3.0 -->
		<script src="template/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
		<!-- ChartJS 1.0.1 -->
		<script src="template/bower_components/chart.js/Chart.min.js" type="text/javascript"></script>
	
	
		<script src="template/plugins/jQueryUI/jquery-ui.min.js" type="text/javascript"></script>

		<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
		<!-- <script src="dist/js/pages/dashboard2.js" type="text/javascript"></script> -->

        <script src="template/bower_components/select2/dist/js/select2.min.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/highcharts-3d.js"></script>
        <script type="text/javascript" src="template/plugins/Highcharts/js/modules/exporting.js"></script>
        <!-- <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script> -->

        <!--<script src="plugins/datepicker/bootstrap-datepicker.js"></script>-->
        <script src="//cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <!-- jQuery 3 -->
        <!-- <script src="template/bower_components/jquery/dist/jquery.min.js"></script> -->
        <!-- Bootstrap 3.3.7 -->
        <!-- <script src="template/bower_components/bootstrap/dist/js/bootstrap.min.js"></script> -->
        <!-- iCheck -->
        <!-- <script src="template/plugins/iCheck/icheck.min.js"></script> -->

        <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->

        <script>
        $('.select2').select2();
        listaIndicacoes();

            // function atualizaUsuario(nome,valor){
            //     $.ajax({
            //         type: 'POST',
            //         url: 'filtroUserLista',
            //         dataType: 'json',
            //         data: 'nome='+nome+'&valor='+valor,
            //         success: function(resposta){
            //             $('#opt_user').empty();
            //             $("#opt_user").append(new Option('Selecione um usuário', ''));
            //             for(var i=0; i<resposta.length;i++){
            //                 $("#opt_user").append(new Option(resposta[i]['name'], resposta[i]['uuid']));
            //             }
            //         }
            //     });
            // }

            function listaIndicacoes(){
                var tabela = '';
                var status = '';
                var nome = '';
                var valor = '';
                var comissao = '';
                var consultor= '';
                var join = '';

                if($('#opt_busca').val() == '' && $('#opt_status').val() == ''){
                    toastr.warning('Digite um valor para a busca');
                    return false;
                }
                
                if($('#opt_status').val() != '')  status = 'status='+$('#opt_status').val();

                if($('#opt_busca').val() == 1){
                    if($('#txt_cpf_cnpj').val() == ''){
                        toastr.warning('Digite um valor para a busca');
                        return false;
                    }
                    var nome = 'nome=cpf_cnpj';
                    var valor = '&valor='+$('#txt_cpf_cnpj').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                else if($('#opt_busca').val() == 2){
                    if($('#txt_telefone').val() == ''){
                        toastr.warning('Digite um valor para a busca');
                        return false;
                    }
                    var nome = 'nome=telefone';
                    var valor = '&valor='+$('#txt_telefone').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                else if($('#opt_busca').val() == 3){
                    if($('#txt_email').val() == ''){
                        toastr.warning('Digite um valor para a busca');
                        return false;
                    }
                    var nome = 'nome=email';
                    var valor = '&valor='+$('#txt_email').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                else if($('#opt_busca').val() == 4){
                    if($('#txt_nome_responsavel').val() == ''){
                        toastr.warning('Digite um valor para a busca');
                        return false;
                    }
                    var nome = 'nome=name_responsavel';
                    var valor = '&valor='+$('#txt_nome_responsavel').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                else if($('#opt_busca').val() == 5){
                    if($('#txt_nome').val() == ''){
                        toastr.warning('Digite um valor para a busca');
                        return false;
                    }
                    var nome = 'nome=name';
                    var valor = '&valor='+$('#txt_nome').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                else if($('#opt_busca').val() == 6){ 
                    if($('#txt_indicador').val() == ''){
                        toastr.warning('Digite um valor para a busca');
                        return false;
                    }
                    // $data2['user_uuid'] = '%'.$_SESSION['user']['id'].'%';
                    // $data2['creator_uuid'] = '%'.$_SESSION['user']['id'].'%';
                    // $join['users']['campo'] = 'uuid';
                    // $join['users']['campo2'] = 'indications.user_uuid';
                        
                    
                    //var join = "&join="+{'users': {"campo":"uuid","campo2":"indications.creator_uuid"}};   
                    
                    join = '&join=1';
                    
                    var nome = 'nome=users.name';    
                   
                    var valor = '&valor='+$('#txt_indicador').val();
                    if($('#opt_status').val() != '')  status = '&status='+$('#opt_status').val();
                }
                

                

                $.ajax({
                    type: 'POST',
                    url: 'filtroIndicacaoLista',
                    dataType: 'json',
                    data: nome+valor+status+join,
                    success: function(resposta){
                        var t = $('#tbIndicacao').dataTable();t.fnDestroy();
                        for(var i=0; i<resposta.length;i++){
                            if(resposta[i]['status'] == 1) status = "<td style='color:orange'><b>Pendente</b>";
                            else if(resposta[i]['status'] == 2) status = "<td><b>Cliente contatado</b>";
                            else if(resposta[i]['status'] == 3) status = "<td><b>Visita Realizada</b>";
                            else if(resposta[i]['status'] == 4) status = "<td><b>Proposta Enviada</b>";
                            else if(resposta[i]['status'] == 5) status = "<td style='color:green'><b>Negócio ganho</b>";
                            else if(resposta[i]['status'] == 6) status = "<td style='color:red'><b>Negócio perdido</b>";
                            else if(resposta[i]['status'] == 7) status = "<td style='color:red'><b>Sem Consultor</b>";
                            else status = "<td style='color:red'><b>Cancelado</b>";
                            
                            if(resposta[i]['commission'] == 1)   comissao = "<td>Fixa";
                            else                                 comissao = "<td>Recorrente";
                            
                            if(resposta[i]['user_name'] == null)   consultor = "<td>Sem Consultor";
                            else                                 consultor = "<td>"+resposta[i]['user_name'];

                            tabela += '<tr id="'+i+'">';
                            tabela += '<td><button type="button" class="btn btn-default btn-xs" onclick="ver_comisao(\''+resposta[i]['uuid']+'\');"><i class="fa fa-eye"></i></button></td>';
                            tabela += '<td>'+resposta[i]['name']+'</td>';
                            tabela += '<td>'+resposta[i]['cpf_cnpj']+'</td>';
                            tabela += '<td>'+resposta[i]['telefone']+'</td>';
                            tabela += '<td>'+resposta[i]['name_responsavel']+'</td>';
                            tabela += '<td>'+resposta[i]['email']+'</td>';
                            tabela += status+'</td>';
                            tabela += comissao+'</td>';
                            tabela += consultor+'</td>';

                            <?php if($user_type != 4){?>
                                tabela += '<td><button onclick="editarIndicacao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                                tabela += '<td><button onclick="excluirIndicacao(\''+resposta[i]['uuid']+'\',\''+i+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-trash-o"></i></button></td>';
                            <?php }?>
                            tabela += '<td><button onclick="ver_observacao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs" title="Ver observações"><i class="fa fa-list"></i></button></td>';                            
                            tabela += '</tr>';
                        }
                        $('#tbIndicacaoBody').html(tabela);

                        
                        $('#tbIndicacao').DataTable({
                            'autoWidth'   : true,
                            'aLengthMenu' :	[[10, 25, 50, -1], [10, 25, 50, "Tudo"]],
                            'oLanguage'   : {"sEmptyTable": "Nenhum registro encontrado", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando 0 até 0 de 0 registros", "sInfoFiltered": "(Filtrados de _MAX_ registros)", "sInfoPostFix": "", "sInfoThousands": ".", "sLengthMenu": "_MENU_ resultados por página", "sLoadingRecords": "Carregando...", "sProcessing": "Processando...", "sZeroRecords": "Nenhum registro encontrado", "sSearch": "Pesquisar", "oPaginate": { "sNext": "Próximo", "sPrevious": "Anterior", "sFirst": "Primeiro", "sLast": "Último" }, "oAria": { "sSortAscending": ": Ordenar colunas de forma ascendente", "sSortDescending": ": Ordenar colunas de forma descendente"}}
                        });
                    }
                });
            }

            function ver_observacao(uuid){
                $.get('getObservacao/'+uuid,function(dados){
                    dados = JSON.parse(dados);
                    var tabela = "";
                    var status = "";
                    
                    for(var i = 0; i<dados.length; i++) {
                        tabela += '<tr>';
                        switch (dados[i]['status']) {
                            case "1":
                                status = 'Pendente';
                                break;
                            case "2":
                                status = 'Cliente contatado';
                                break;
                            case "3":
                                status = 'Visita Realizada';
                                break;
                            case "4":
                                status = 'Proposta Enviada';
                                break;
                            case "5":
                                status = 'Negocio ganho';
                                break;
                            case "6":
                                status = 'Negocio perdido';
                                break;
                            case "7":
                                status = 'Sem Consultor';
                                break;
                            default:
                                break;
                        }
                        var data = dados[i]['create_time'];
                        
                        var vetor = data.split(" ");
                        var vetor2 = vetor[0].split("-");
                        
                        var ano = vetor2[0];
                        var mes = vetor2[1];
                        var dia = vetor2[2];
                        var horario = vetor[1];

                        tabela += "<td>"+status+"</td>";
                        tabela += '<td>'+dados[i]['observation']+'</td>';
                        tabela += "<td>"+dia+"/"+mes+"/"+ano+" - "+horario+"</td>";

                        tabela += '</tr>';
                    }
                    $('#tbody_observation').html(tabela);
                    $('#modal_observation').modal(); 
                });
            }

            function modal_adicionar_observacao(){
                $('#txt_observation_modal').val("");
                $('#modal_add_observation').modal();
            }

            function add_observacao(){
                var observacao = $('#txt_observation_modal').val();
                if(observacao == "" || observacao == " " || !observacao){
                    toastr.warning('Digite uma observação');
                    return false;
                }
                var status = $('#txt_status_modal').val();
                var uuid = $('#opt_indication_uuid').val();

                $.ajax({
                    type: 'POST',
                    url: '/addObservacao',
                    data: 'uuid='+uuid+'&status='+status+'&observation='+observacao,
                    dataType: 'json',
                    success: function (dados) {
                        if(dados){
                            toastr.success('Adicionado');
                            $('#modal_add_observation').modal('hide');
                            var coluna = "<tr>";
                            switch (status) {
                                case "1":
                                    status = 'Pendente';
                                    break;
                                case "2":
                                    status = 'Cliente contatado';
                                    break;
                                case "3":
                                    status = 'Visita Realizada';
                                    break;
                                case "4":
                                    status = 'Proposta Enviada';
                                    break;
                                case "5":
                                    status = 'Negocio ganho';
                                    break;
                                case "6":
                                    status = 'Negocio perdido';
                                    break;
                                case "7":
                                    status = 'Sem Consultor';
                                    break;
                                default:
                                    break;
                            }
                            coluna += "<td>"+dados.status+"</td>";
                            coluna += "<td>"+dados.observacao+"</td>";
                            coluna += "<td>"+dados.data+"</td></tr>";
                            $('#table_observation').append(coluna);
                        }
                        else{
                            toastr.error('Erro ao adicionar');
                        }
                    }
                });
            }

            function editarComissao(uuid){
                $("#myForm").attr("action","editaComissao/"+uuid);    
                $("#myForm").submit();
            }

            function excluirComissao(uuid,num){
                if(confirm("Deseja deletar a comissão?")){
                    $.ajax({
                    type: 'POST',
                    url: '/excluiComissao',
                    dataType: 'json',
                    data: 'uuid='+uuid,
                    success: function(resposta){

                        
                        if(resposta){
                            $("#"+num+"").remove();
                            toastr.success('Deletado');
                        }
                    }
                    
                    });
                }
            }

            function payCommission(uuid,i){
                var r = confirm("Deseja pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Pago <button onclick='unpaidCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>");
                            $('#pay'+i).css("color","green");
                        }
                        else{
                            toastr.error('Falha ao Pagar');    
                        }
                    });
                }
            }

            function unpaidCommission(uuid,i){
                var r = confirm("Deseja não pagar a comissão?");
                if(r == true){
                    $.get('payCommission/'+uuid,function(data){
                        var resposta = JSON.parse(data);
                        if(data == "true"){
                            $('#pay'+i).html("Não Pago <button onclick='payCommission(\""+uuid+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>");
                            $('#pay'+i).css("color","red");
                        }
                        else{
                            toastr.error('Falha ao Não Pagar');    
                        }
                    });
                }
            }

            function editarIndicacao(uuid){
                $("#myForm").attr("action","editaIndicacao/"+uuid);    
                $("#myForm").submit();
            }

            function excluirIndicacao(uuid,num){
                if(confirm("Deseja deletar a indicação?")){
                    $.ajax({
                    type: 'POST',
                    url: 'excluiIndicacao',
                    dataType: 'json',
                    data: 'uuid='+uuid,
                    success: function(resposta){
                        if(resposta){
                            $("#"+num+"").remove();
                            toastr.success('Deletado');
                        }
                    }
                    
                    });
                }
            }

            function ver_comisao(uuid){
                $('#tbody_commission').html('');
                var t = $('#table_commissions').dataTable();t.fnDestroy();
                $.get('/getCommissionsIndication/'+uuid,function(data){
                    var resposta = JSON.parse(data);
                    var data = new Date();
                    var mes_atual = data.getMonth()+1;
                    var ano_atual = data.getFullYear();

                    var tabela = "";
                    var status = "";
                    var dia = '';
                    var mes = '';
                    var ano = '';
                    var data = '';
                    var observation = '';
                    var botao = '';
                    for(var i=0; i<resposta.length;i++){

                        ano  = resposta[i]['date'].split("-")[0];
                        mes  = resposta[i]['date'].split("-")[1];
                        dia  = resposta[i]['date'].split("-")[2];

                        

                        if(mes_atual == mes && ano_atual == ano)    data = "-> "+dia + '/' + (mes) + '/' + (ano);
                        else                                        data = dia + '/' + (mes) + '/' + (ano);

                        if(resposta[i]['observation'] == null)  observation = "<td></td>";
                        else                                    observation = "<td>"+resposta[i]['observation']+"</td>";
                        
                        botao = '';
                        <?php if($user_type == 1 || $user_type == 2){?>
                            if(resposta[i]['paid'] == 1)    botao = "<button onclick='payCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Pagar' class='btn btn-default btn-xs'><i class='fa fa-thumbs-down'></i></button>";
                            else                            botao = "<button onclick='unpaidCommission(\""+resposta[i]['uuid']+"\",\""+i+"\");' type='button' title='Não Pago' class='btn btn-default btn-xs'><i class='fa fa-thumbs-up'></i></button>";
                        <?php }?>

                        if(resposta[i]['paid'] == 1)    status = "<td style='color:red' id=pay"+i+">Não Pago "+botao+"</td>";
                        else                            status = "<td style='color:green' id=pay"+i+">Pago "+botao+"</td>";
                            
                        tabela += "<tr id='"+resposta[i]['uuid']+"'>";
                        tabela += '<td>R$'+(resposta[i]['value_commission']/100)+'</td>';
                        tabela += '<td>'+data+'</td>';
                        tabela += status;
                        tabela += observation;
                        <?php if($user_type == 1 || $user_type == 2){?>
                            tabela += '<td><button onclick="editarComissao(\''+resposta[i]['uuid']+'\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button></td>';
                            tabela += '<td><button onclick="excluirComissao(\''+resposta[i]['uuid']+'\',\''+resposta[i]['uuid']+'4\');" type="button" class="btn btn-default btn-xs"><i class="fa fa-trash-o"></i></button></td>';
                        <?php }else{?>
                            tabela += '<td></td>'
                            tabela += '<td></td>'
                        <?php }?>
                        tabela += '</tr>';

                    }
                    $('#tbody_commission').html(tabela);

                    $('#table_commissions').DataTable({
                        'autoWidth'   : true,
                        'aLengthMenu' :	[[10, 25, 50, -1], [10, 25, 50, "Tudo"]],
                        'oLanguage'   : {"sEmptyTable": "Nenhum registro encontrado", "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros", "sInfoEmpty": "Mostrando 0 até 0 de 0 registros", "sInfoFiltered": "(Filtrados de _MAX_ registros)", "sInfoPostFix": "", "sInfoThousands": ".", "sLengthMenu": "_MENU_ resultados por página", "sLoadingRecords": "Carregando...", "sProcessing": "Processando...", "sZeroRecords": "Nenhum registro encontrado", "sSearch": "Pesquisar", "oPaginate": { "sNext": "Próximo", "sPrevious": "Anterior", "sFirst": "Primeiro", "sLast": "Último" }, "oAria": { "sSortAscending": ": Ordenar colunas de forma ascendente", "sSortDescending": ": Ordenar colunas de forma descendente"}}
                    });
                });
                
                $('#modal_commission').modal();
            }

            function carregaIndicadores(){
                $.get('getCreators',function(data){
                    var opcoes = "<option value=''>Escolha um Indicador</option>";
                    var data = JSON.parse(data);
                    for(var i=0; i<data.length;i++){
                        opcoes += "<option value='"+data[i]['uuid']+"'>"+data[i]['name']+"</option>"; 
                    }
                    $('#opt_creator').html(opcoes);
                });
            }

            $(document).ready(function() {
				
				toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1500",
                    "timeOut": "9000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
                
                // $.ajax({
                //     type: 'POST',
                //     url: 'filtroIndicacaoLista',
                //     dataType: 'json',
                //     data: 'nome=email&valor=@',
                //     success: function(resposta){
                //         $('#opt_indication').empty();
                //         $("#opt_indication").append(new Option('Selecione uma Indicação', ''));
                //         for(var i=0; i<resposta.length;i++){
                //             $("#opt_indication").append(new Option(resposta[i]['name'], resposta[i]['uuid']));
                //         }
                //     }
                // });
                

                <?php 
                    if(isset($validate[0])){
                        foreach($validate[0] as $value){
                            foreach($value as $mensagem){
                                echo "toastr.error('{$mensagem}');";
                            }
                        }
                    }
                    else if(isset($success[0]))
                        echo "toastr.success('".$success[0]."');";
                    
                    else if(isset($error[0]))
                        echo "toastr.error('".$error[0]."');";    
                 ?>
			});
        </script>	
    </body>
</html>